// ============================================================================
// WORDRUSH ARENA - Embedded Native C++ Lexical Word Bank & Anagram Repository
// ============================================================================

#include "lexicon_data.hpp"
#include <cstring>
#include <cctype>
#include <algorithm>

namespace WordRush {

const LexiconEntry LexiconData::CORE_DICTIONARY[] = {
    // ------------------------------------------------------------------------
    // EASY LEVEL (4-LETTER WORDS)
    // ------------------------------------------------------------------------
    {"ARCH", 4, "EASY", "Architecture", "A curved symmetrical structure spanning an opening.", "Curved bridge or doorway structure", 120},
    {"BARK", 4, "EASY", "Nature", "The outer covering of a tree, or the sound made by a dog.", "Sound of a dog or tree exterior", 120},
    {"BIRD", 4, "EASY", "Fauna", "A warm-blooded feathered creature with wings.", "Feathered flying creature in sky", 120},
    {"BLUE", 4, "EASY", "Color", "The color of the clear sky and deep ocean.", "Color of clear sky on sunny day", 120},
    {"BOAT", 4, "EASY", "Transport", "A small watercraft propelled by oars, sails, or engine.", "Floats on water carrying passengers", 120},
    {"BOLD", 4, "EASY", "Adjective", "Showing willingness to take risks; courageous.", "Fearless, brave, or thick font", 120},
    {"BOND", 4, "EASY", "Relationship", "A strong connection or legal mutual agreement.", "A tight friendship or chemical tie", 120},
    {"CAMP", 4, "EASY", "Outdoors", "A place with temporary accommodations of huts or tents.", "Tents outdoors by a campfire", 120},
    {"CARE", 4, "EASY", "Emotion", "Provision of what is necessary for health and welfare.", "Giving warmth, looking after someone", 120},
    {"CAST", 4, "EASY", "Action", "To throw forcefully, or the actors in a theatrical play.", "Throw a fishing line or actors in movie", 120},
    {"CLAY", 4, "EASY", "Material", "A stiff, fine-grained earth used in pottery.", "Molded by sculptors on pottery wheel", 120},
    {"COLD", 4, "EASY", "Weather", "At a low temperature, especially when compared to human body.", "Opposite of hot, frosty winter chill", 120},
    {"DARK", 4, "EASY", "Lighting", "With little or no light.", "Absence of light at deep night", 120},
    {"DAWN", 4, "EASY", "Time", "The first appearance of light in the sky before sunrise.", "Morning sunrise horizon waking up", 120},
    {"DESK", 4, "EASY", "Furniture", "A piece of furniture with a flat top used for writing.", "Where you work or study with a laptop", 120},
    {"DIET", 4, "EASY", "Health", "The kinds of food that a person, animal, or community eats.", "Healthy meal nutrition plan", 120},
    {"DUST", 4, "EASY", "Nature", "Fine, dry powder consisting of tiny particles of earth.", "Dry particles wiped from furniture", 120},
    {"ECHO", 4, "EASY", "Sound", "A sound caused by reflection of sound waves from a surface.", "Bouncing acoustic sound wave repeat", 120},
    {"EDIT", 4, "EASY", "Writing", "Prepare text or media by modifying and correcting.", "Revise writing or trim video frames", 120},
    {"FACE", 4, "EASY", "Anatomy", "The front part of a person's head from forehead to chin.", "Eyes, nose, mouth and smile features", 120},
    {"FARM", 4, "EASY", "Agriculture", "An area of land devoted to growing crops and raising animals.", "Tractors, red barn, corn and livestock", 120},
    {"FAST", 4, "EASY", "Speed", "Moving or capable of moving at high speed.", "Quick, rapid, high-speed velocity", 120},
    {"FISH", 4, "EASY", "Fauna", "A limbless cold-blooded vertebrate animal with gills.", "Swims in rivers and oceans with fins", 120},
    {"FLAG", 4, "EASY", "Symbol", "A piece of cloth with distinctive design used as a symbol.", "National banner waving on tall flagpole", 120},
    {"FLOW", 4, "EASY", "Physics", "Move along in a steady, continuous stream.", "Stream of fresh water gliding down river", 120},
    {"FROG", 4, "EASY", "Fauna", "A tailless amphibian with long legs adapted for leaping.", "Green leaping pond amphibian with croak", 120},
    {"GAME", 4, "EASY", "Entertainment", "A competitive activity or sport played according to rules.", "Fun playful contest with points and rules", 120},
    {"GLOW", 4, "EASY", "Light", "Give out steady light without a violent flame.", "Soft luminous radiance in darkness", 120},
    {"GOLD", 4, "EASY", "Mineral", "A precious yellow metallic chemical element.", "Shiny yellow precious royal treasure metal", 120},
    {"GRID", 4, "EASY", "Geometry", "A network of lines that cross each other to form squares.", "Checkerboard squares or matrix layout", 120},
    {"HAWK", 4, "EASY", "Fauna", "A diurnal bird of prey with broad rounded wings and keen sight.", "Sharp-eyed raptor hunting from high sky", 120},
    {"HERO", 4, "EASY", "Archetype", "A person admired for courage, outstanding achievements.", "Courageous savior of justice and good", 120},
    {"HOPE", 4, "EASY", "Emotion", "A feeling of expectation and desire for a certain thing to happen.", "Optimistic wish for bright future", 120},
    {"IRON", 4, "EASY", "Metal", "A strong, hard magnetic silvery-gray metallic element.", "Strong metallic construction ore and anvil", 120},
    {"JUMP", 4, "EASY", "Action", "Push oneself off a surface into the air using muscles.", "Leap off ground with spring in legs", 120},
    {"KING", 4, "EASY", "Royalty", "The male ruler of an independent state or kingdom.", "Crown-bearing royal sovereign ruler", 120},
    {"LAKE", 4, "EASY", "Geography", "A large body of water surrounded by land.", "Calm freshwater body enclosed by shores", 120},
    {"LION", 4, "EASY", "Fauna", "A large carnivorous feline of Africa with golden mane.", "Mighty golden king of the jungle pride", 120},
    {"MOON", 4, "EASY", "Astronomy", "The natural satellite of the earth, visible by night.", "Glowing night satellite orbiting earth", 120},
    {"NEST", 4, "EASY", "Nature", "A structure built by birds to hold eggs and shelter young.", "Twig cradle built high in branches", 120},
    {"PARK", 4, "EASY", "Outdoors", "A large public green area used for recreation.", "Public green lawn with trees and benches", 120},
    {"RAIN", 4, "EASY", "Weather", "Moisture condensed from the atmosphere that falls in drops.", "Cloud precipitation watering forests", 120},
    {"ROCK", 4, "EASY", "Geology", "The solid mineral material forming part of the earth surface.", "Hard geological boulder or stony hill", 120},
    {"ROSE", 4, "EASY", "Flora", "A prickly bush or shrub that bears fragrant flowers.", "Classic sweet fragrant flower with thorns", 120},
    {"SAIL", 4, "EASY", "Nautical", "A piece of fabric spread to catch the wind on a boat.", "Canvas cloth propelling ship across ocean", 120},
    {"SAND", 4, "EASY", "Geology", "Loose granular substance resulting from erosion of rocks.", "Warm golden granules on tropical beach", 120},
    {"STAR", 4, "EASY", "Cosmos", "A luminous point in the night sky that is a celestial body.", "Twinkling burning sun in distant cosmos", 120},
    {"TIDE", 4, "EASY", "Nature", "The alternate rising and falling of the ocean sea level.", "Ocean water rising and falling on beaches", 120},
    {"TIED", 4, "EASY", "Verb", "Fastened or bound securely with a knot or string.", "Bound securely with cord, rope, or knot", 120},
    {"WIND", 4, "EASY", "Weather", "The perceptible natural movement of the air blowing.", "Gentle breezy gale rustling autumn leaves", 120},
    {"WOLF", 4, "EASY", "Fauna", "A wild carnivorous mammal of the dog family living in packs.", "Pack hunting canine howling at full moon", 120},
    {"YARD", 4, "EASY", "Property", "A piece of ground adjoining a building, grass-covered.", "Grassy lawn area surrounding suburban home", 120},
    {"ZEAL", 4, "EASY", "Emotion", "Great energy or enthusiasm in pursuit of a cause or objective.", "Fervent passion, fiery vigor, and drive", 120},

    // ------------------------------------------------------------------------
    // MEDIUM LEVEL (5-LETTER WORDS)
    // ------------------------------------------------------------------------
    {"ARENA", 5, "MEDIUM", "Architecture", "A level area surrounded by seats for sports and entertainment.", "Battleground colosseum where gladiators clash", 150},
    {"BLAZE", 5, "MEDIUM", "Fire", "A very large or fiercely burning fire.", "Intense crackling radiant inferno flame", 150},
    {"CANDY", 5, "MEDIUM", "Food", "A sweet confection made with sugar or syrup flavored with fruit.", "Sugary colorful confectionery treat", 150},
    {"CRANE", 5, "MEDIUM", "Machinery", "A tall machine used for moving heavy objects, or tall bird.", "Tall lifting hoist or long-legged bird", 150},
    {"CYBER", 5, "MEDIUM", "Technology", "Relating to electronic communication networks and computers.", "Digital electronic web matrix network", 150},
    {"DELTA", 5, "MEDIUM", "Geography", "A triangular tract of sediment deposited at river mouth.", "Triangular river estuary mouth sediment", 150},
    {"EAGLE", 5, "MEDIUM", "Fauna", "A large bird of prey with massive hooked bill and long wings.", "Majestic soaring raptor bird of prey", 150},
    {"FLAME", 5, "MEDIUM", "Fire", "A hot glowing body of ignited gas produced by combustion.", "Hot glowing tongue of campfire heat", 150},
    {"FROST", 5, "MEDIUM", "Weather", "A deposit of small white ice crystals formed on ground.", "Crisp white crystalline morning ice film", 150},
    {"GHOST", 5, "MEDIUM", "Paranormal", "An apparition of a dead person which is believed to appear.", "Ethereal translucent spirit apparition", 150},
    {"LUNAR", 5, "MEDIUM", "Astronomy", "Resembling or relating to the moon.", "Pertaining to moon phases and orbit", 150},
    {"MAGIC", 5, "MEDIUM", "Fantasy", "The power of influencing events by using mysterious forces.", "Arcane wizard sorcery and enchantment", 150},
    {"NINJA", 5, "MEDIUM", "Combat", "A person skilled in traditional Japanese covert martial arts.", "Stealthy masked shinobi warrior of night", 150},
    {"ORBIT", 5, "MEDIUM", "Astronomy", "The gravitationally curved trajectory of an object around a star.", "Curved path of planet around the sun", 150},
    {"PIXEL", 5, "MEDIUM", "Display", "A minute area of illumination on a display screen.", "Smallest square digital color dot on screen", 150},
    {"PRISM", 5, "MEDIUM", "Optics", "A solid geometric shape that refracts light into rainbow colors.", "Glass crystal splitting light into rainbow", 150},
    {"PULSE", 5, "MEDIUM", "Biology", "The rhythmic throbbing of arteries as blood is propelled.", "Rhythmic heartbeat arterial rhythm", 150},
    {"RAVEN", 5, "MEDIUM", "Fauna", "A large heavily built crow with obsidian black plumage.", "Wise black bird of folklore and mystery", 150},
    {"RIDER", 5, "MEDIUM", "Person", "A person who rides a horse, bicycle, or motorcycle.", "Pilot traveling mounted on steed or bike", 150},
    {"SOLAR", 5, "MEDIUM", "Astronomy", "Relating to or determined by the sun.", "Powered by warm golden sunshine rays", 150},
    {"SPARK", 5, "MEDIUM", "Energy", "A small fiery particle thrown off from a fire or electrical arc.", "Tiny bright flash of ignited fire", 150},
    {"STORM", 5, "MEDIUM", "Weather", "A violent disturbance of the atmosphere with strong winds.", "Tempest with torrential rain and thunder", 150},
    {"SWORD", 5, "MEDIUM", "Weapon", "A weapon with a long metal blade and hilt with hand guard.", "Bladed steel duel weapon of knights", 150},
    {"TIGER", 5, "MEDIUM", "Fauna", "A very large solitary cat with a yellow coat striped with black.", "Striped orange apex predator feline", 150},
    {"TITAN", 5, "MEDIUM", "Mythology", "A person or thing of very great strength or importance.", "Immense mythological giant of raw power", 150},
    {"VIPER", 5, "MEDIUM", "Fauna", "A venomous snake that has large hinged fangs.", "Coiled venomous serpent with sharp fangs", 150},

    // ------------------------------------------------------------------------
    // HARD LEVEL (6-LETTER WORDS)
    // ------------------------------------------------------------------------
    {"BATTLE", 6, "HARD", "Conflict", "A sustained fight between large organized armed forces.", "Clash of opposing armies on field", 180},
    {"CASTLE", 6, "HARD", "Architecture", "A large fortified building or group of buildings.", "Stone medieval fortress with moat and towers", 180},
    {"CIPHER", 6, "HARD", "Cryptography", "A secret or disguised way of writing; a code.", "Encrypted coded riddle needing decryption", 180},
    {"DANGER", 6, "HARD", "Safety", "The possibility of suffering harm or injury.", "Hazardous risk or warning alert sign", 180},
    {"DRAGON", 6, "HARD", "Mythology", "A mythical monster like a giant reptile breathing fire.", "Fire-breathing winged mythical scaly beast", 180},
    {"ENERGY", 6, "HARD", "Physics", "The strength and vitality required for sustained activity.", "Dynamic power, electricity, or vital stamina", 180},
    {"ENGINE", 6, "HARD", "Mechanical", "A machine with moving parts that converts power into motion.", "Mechanical generator driving vehicle wheels", 180},
    {"FOREST", 6, "HARD", "Biome", "A large area covered chiefly with trees and undergrowth.", "Vast dense woodland with towering pines", 180},
    {"GALAXY", 6, "HARD", "Cosmos", "A system of millions or billions of stars with gas and dust.", "Swirling cosmic spiral of stars and nebulae", 180},
    {"HARBOR", 6, "HARD", "Maritime", "A place on the coast where vessels may find shelter.", "Sheltered marine haven for docking ships", 180},
    {"ISLAND", 6, "HARD", "Geography", "A piece of land surrounded entirely by water.", "Tropical landmass ringed by ocean surf", 180},
    {"JUNGLE", 6, "HARD", "Biome", "An area of land overgrown with dense forest and vegetation.", "Lush tropical rainforest dense with vines", 180},
    {"KNIGHT", 6, "HARD", "History", "A man awarded a nonhereditary title by a monarch.", "Armored chivalrous mounted warrior", 180},
    {"LEGEND", 6, "HARD", "Storytelling", "A traditional story popularly regarded as historical.", "Mythic historic heroic tale of old", 180},
    {"MAGNET", 6, "HARD", "Physics", "A piece of iron that produces an external magnetic field.", "Polarized metal pulling iron filings", 180},
    {"MIRROR", 6, "HARD", "Optics", "A reflective surface of glass with silvery metallic coating.", "Glass surface reflecting true image", 180},
    {"PLANET", 6, "HARD", "Astronomy", "A celestial body moving in an elliptical orbit around a star.", "Spherical terrestrial or gas world in orbit", 180},
    {"PUZZLE", 6, "HARD", "Gaming", "A game, problem, or toy that tests a person's ingenuity.", "Intricate enigma, riddle, or brainteaser", 180},
    {"ROCKET", 6, "HARD", "Aerospace", "A cylindrical projectile propelled into high atmosphere.", "Orbital booster blasting into the cosmos", 180},
    {"SECRET", 6, "HARD", "Information", "Not known or seen or not meant to be known or seen by others.", "Hidden confidential truth or cipher", 180},
    {"SHIELD", 6, "HARD", "Armor", "A broad piece of armor carried on the arm for defense.", "Defensive protective barrier held in combat", 180},
    {"SILVER", 6, "HARD", "Mineral", "A precious shiny grayish-white metallic element.", "Shining lustrous precious metal coin", 180},
    {"SUMMER", 6, "HARD", "Season", "The warmest season of the year between spring and autumn.", "Warmest sunny season of beaches and sun", 180},
    {"TARGET", 6, "HARD", "Precision", "A person, object, or place selected as the aim of attack.", "Concentric circle bullseye mark for arrows", 180},
    {"WIZARD", 6, "HARD", "Fantasy", "A person who has magical powers, in legends and fairy tales.", "Staff-bearing mystical arcane sorcerer", 180}
};

const size_t LexiconData::CORE_DICTIONARY_SIZE = sizeof(CORE_DICTIONARY) / sizeof(CORE_DICTIONARY[0]);

const char* const LexiconData::VOCABULARY_LIST_3[] = {
    "ACT", "ADD", "AGE", "AGO", "AID", "AIM", "AIR", "ALL", "AND", "ANT", "ANY", "APE",
    "ARC", "ARM", "ART", "ASH", "ASK", "ATE", "AWE", "AXE", "BAD", "BAG", "BAN", "BAR",
    "BAT", "BAY", "BED", "BEE", "BEG", "BET", "BID", "BIG", "BIN", "BIT", "BOB", "BOW",
    "BOX", "BOY", "BUG", "BUS", "BUT", "BUY", "CAB", "CAN", "CAP", "CAR", "CAT", "COW",
    "CRY", "CUP", "CUT", "DAD", "DAM", "DAY", "DEN", "DEW", "DID", "DIE", "DIG", "DIM",
    "DIP", "DOG", "DOT", "DRY", "DUE", "DUG", "DYE", "EAR", "EAT", "EGG", "EGO", "ELF",
    "ELM", "END", "ERA", "EVE", "EYE", "FAN", "FAR", "FAT", "FED", "FEE", "FEW", "FIG",
    "FIT", "FIX", "FLY", "FOE", "FOG", "FOR", "FOX", "FRY", "FUN", "FUR", "GAP", "GAS",
    "GEL", "GEM", "GET", "GIG", "GOD", "GOT", "GUM", "GUN", "GUT", "GUY", "GYM", "HAD",
    "HAM", "HAS", "HAT", "HAY", "HEN", "HER", "HID", "HIM", "HIP", "HIS", "HIT", "HOP",
    "HOT", "HOW", "HUB", "HUG", "HUM", "HUT", "ICE", "ILL", "INK", "INN", "ION", "IRE",
    "IVY", "JAM", "JAR", "JAW", "JAY", "JET", "JIG", "JOB", "JOG", "JOY", "JUG", "KEY",
    "KID", "KIN", "KIT", "LAB", "LAD", "LAP", "LAW", "LAY", "LED", "LEG", "LET", "LID",
    "LIE", "LIP", "LIT", "LOG", "LOT", "LOW", "MAD", "MAN", "MAP", "MAT", "MAY", "MEN",
    "MET", "MID", "MIX", "MOM", "MOP", "MUD", "MUG", "NET", "NEW", "NIL", "NOD", "NOT",
    "NOW", "NUT", "OAK", "OAR", "ODD", "OFF", "OFT", "OIL", "OLD", "ONE", "OPT", "ORB",
    "OUR", "OUT", "OWL", "OWN", "PAD", "PAN", "PAR", "PAT", "PAW", "PAY", "PEA", "PEG",
    "PEN", "PET", "PIE", "PIG", "PIN", "PIT", "PLY", "POD", "POP", "POT", "PRO", "PUB",
    "PUN", "PUP", "PUT", "RAG", "RAM", "RAN", "RAP", "RAT", "RAW", "RAY", "RED", "RIB",
    "RID", "RIG", "RIM", "RIP", "ROB", "ROD", "ROT", "ROW", "RUB", "RUG", "RUN", "RUT",
    "RYE", "SAD", "SAG", "SAP", "SAT", "SAW", "SAY", "SEA", "SEE", "SET", "SEW", "SHE",
    "SHY", "SIN", "SIP", "SIR", "SIT", "SKI", "SKY", "SLY", "SOB", "SON", "SOW", "SOY",
    "SPA", "SPY", "SUM", "SUN", "TAB", "TAG", "TAN", "TAP", "TAR", "TAX", "TEA", "TED",
    "TEE", "TEN", "THE", "THY", "TIE", "TIN", "TIP", "TOE", "TON", "TOO", "TOP", "TOW",
    "TOY", "TRY", "TUB", "TUG", "TWO", "URN", "USE", "VAN", "VAT", "VET", "VIA", "VOW",
    "WAG", "WAR", "WAS", "WAY", "WEB", "WED", "WET", "WHO", "WHY", "WIG", "WIN", "WIT",
    "WOE", "WON", "YAK", "YAM", "YAP", "YAW", "YEA", "YES", "YET", "YOU", "ZIP", "ZOO"
};

const size_t LexiconData::VOCABULARY_LIST_3_SIZE = sizeof(VOCABULARY_LIST_3) / sizeof(VOCABULARY_LIST_3[0]);

const char* const LexiconData::VOCABULARY_LIST_4[] = {
    "ACED", "ACES", "ACHE", "ACID", "ACRE", "ACTS", "AGED", "AGES", "AIDE", "AIDS", "AIMS",
    "AIRS", "AJAR", "ALLY", "ALMS", "ALOE", "ALPS", "ALSO", "ALTO", "AMEN", "AMID", "AMPS",
    "ANEW", "ANTS", "APES", "APEX", "APPS", "AQUA", "ARCH", "AREA", "ARID", "ARMS", "ARMY",
    "ARTS", "ASHY", "ASKS", "ATOM", "AUNT", "AURA", "AUTO", "AVID", "AVOW", "AWAY", "AXES",
    "AXIS", "AXLE", "BABE", "BABY", "BACK", "BADE", "BAIL", "BAIT", "BAKE", "BALD", "BALE",
    "BALL", "BALM", "BAND", "BANE", "BANG", "BANK", "BARE", "BARK", "BARN", "BARS", "BASE",
    "BASH", "BASK", "BASS", "BATE", "BATH", "BATS", "BEAM", "BEAN", "BEAR", "BEAT", "BEAU",
    "BEEF", "BEEN", "BEER", "BEES", "BEET", "BEGS", "BELL", "BELT", "BEND", "BENT", "BEST",
    "BETA", "BETS", "BIAS", "BIDE", "BIDS", "BIKE", "BILE", "BILL", "BIND", "BINS", "BIRD",
    "BITE", "BITS", "BLAB", "BLED", "BLEW", "BLIP", "BLOB", "BLOT", "BLOW", "BLUE", "BLUR",
    "BOAR", "BOAT", "BOBS", "BODE", "BODY", "BOIL", "BOLD", "BOLE", "BOLL", "BOLT", "BOMB",
    "BOND", "BONE", "BONY", "BOOK", "BOOM", "BOON", "BOOT", "BORE", "BORN", "BOSS", "BOTH",
    "BOUT", "BOWL", "BOWS", "BOYS", "BRAG", "BRAN", "BRAS", "BRAT", "BRAY", "BRED", "BREW",
    "BRIM", "BROW", "BUCK", "BUDS", "BUFF", "BUGS", "BULB", "BULK", "BULL", "BUMP", "BUMS",
    "BUNT", "BUOY", "BURN", "BURY", "BUSH", "BUSY", "BUTE", "BUTS", "BUTT", "BUYS", "BUZZ",
    "CAFE", "CAGE", "CAKE", "CALF", "CALL", "CALM", "CAME", "CAMP", "CANE", "CANS", "CAPE",
    "CAPS", "CARD", "CARE", "CARP", "CARS", "CART", "CASE", "CASH", "CASK", "CAST", "CATS",
    "CAVE", "CEDE", "CELL", "CENT", "CHAD", "CHAP", "CHAT", "CHEF", "CHEW", "CHIN", "CHIP",
    "CHOP", "CHUM", "CITE", "CITY", "CLAD", "CLAM", "CLAN", "CLAP", "CLAW", "CLAY", "CLIP",
    "CLOD", "CLOG", "CLOP", "CLOT", "CLUB", "CLUE", "COAL", "COAT", "COAX", "COCK", "CODE",
    "COIL", "COIN", "COKE", "COLD", "COLT", "COMA", "COMB", "COME", "CONE", "COOK", "COOL",
    "COOP", "COPE", "COPS", "COPY", "CORD", "CORE", "CORK", "CORN", "COST", "COSY", "COTS",
    "COUP", "COVE", "COWL", "COWS", "COZY", "CRAB", "CRAG", "CRAM", "CRAN", "CRAP", "CREW",
    "CRIB", "CROP", "CROW", "CRUB", "CRUD", "CRUX", "CUBE", "CUBS", "CUED", "CUES", "CUFF",
    "CULL", "CULT", "CUPS", "CURB", "CURD", "CURE", "CURL", "CURT", "CUSP", "CUTE", "CUTS",
    "CYST", "CZAR", "DADO", "DAIS", "DALE", "DAME", "DAMP", "DAMS", "DANK", "DARE", "DARK",
    "DART", "DASH", "DATA", "DATE", "DAWN", "DAYS", "DAZE", "DEAD", "DEAF", "DEAL", "DEAN",
    "DEAR", "DEBT", "DECK", "DEED", "DEEM", "DEEP", "DEER", "DEFT", "DEFY", "DELI", "DELL",
    "DENT", "DENY", "DESK", "DIAL", "DICE", "DIED", "DIES", "DIET", "DIGS", "DIME", "DINE",
    "DING", "DINT", "DIPS", "DIRE", "DIRT", "DISC", "DISH", "DISK", "DIVE", "DOCK", "DOCS",
    "DODO", "DOER", "DOES", "DOGS", "DOLE", "DOLL", "DOLT", "DOME", "DONE", "DOOM", "DOOR",
    "DOPE", "DOSE", "DOTE", "DOTH", "DOTS", "DOVE", "DOWN", "DRAB", "DRAG", "DRAM", "DRAW",
    "DREW", "DRIP", "DROP", "DRUB", "DRUG", "DRUM", "DUAL", "DUCK", "DUCT", "DUDE", "DUDS",
    "DUEL", "DUES", "DUET", "DUFF", "DUKE", "DULL", "DULY", "DUMB", "DUMP", "DUNE", "DUNG",
    "DUNK", "DUSK", "DUST", "DUTY", "DYAD", "DYED", "DYES", "EACH", "EARL", "EARN", "EARS",
    "EASE", "EAST", "EASY", "EATS", "ECHO", "EDDY", "EDGE", "EDGY", "EDIT", "EELS", "EGGS",
    "EGOS", "ELAN", "ELKS", "ELMS", "ELSE", "EMIR", "EMIT", "ENDS", "ENVY", "EPIC", "EPOS",
    "ERAS", "ERGO", "ERRS", "ETCH", "EVEN", "EVER", "EVES", "EVIL", "EXAM", "EXIT", "EXPO",
    "EYED", "EYES", "FACE", "FACT", "FADE", "FAIL", "FAIR", "FAKE", "FALL", "FAME", "FANG",
    "FANS", "FARE", "FARM", "FAST", "FATE", "FATS", "FAWN", "FEAR", "FEAT", "FEED", "FEEL",
    "FEES", "FEET", "FELL", "FELT", "FEND", "FERN", "FEST", "FETE", "FEUD", "FIAT", "FIEF",
    "FIGS", "FILE", "FILL", "FILM", "FIND", "FINE", "FINS", "FIRE", "FIRM", "FISH", "FIST",
    "FITS", "FIVE", "FLAG", "FLAK", "FLAP", "FLAT", "FLAW", "FLAX", "FLEA", "FLED", "FLEE",
    "FLEW", "FLEX", "FLIP", "FLIT", "FLOE", "FLOG", "FLOP", "FLOW", "FLUE", "FOAL", "FOAM",
    "FOES", "FOIL", "FOLD", "FOLK", "FOND", "FONT", "FOOD", "FOOL", "FOOT", "FORD", "FORE",
    "FORK", "FORM", "FORT", "FOUL", "FOUR", "FOWL", "FOXY", "FRAY", "FREE", "FRET", "FROG",
    "FROM", "FUEL", "FULL", "FUME", "FUND", "FURS", "FURY", "FUSE", "FUSS", "FUZZ", "GAGE",
    "GAIN", "GAIT", "GALA", "GALE", "GALL", "GAME", "GANG", "GAOL", "GAPE", "GAPS", "GARB",
    "GASH", "GASP", "GATE", "GAVE", "GAZE", "GEAR", "GEEK", "GEMS", "GENE", "GENT", "GERM",
    "GETS", "GIFT", "GILD", "GILL", "GILT", "GIRD", "GIRL", "GIST", "GIVE", "GLAD", "GLEE",
    "GLEN", "GLIB", "GLIM", "GLOB", "GLOP", "GLOW", "GLUE", "GLUM", "GLUT", "GOAD", "GOAL",
    "GOAT", "GODS", "GOLD", "GOLF", "GONE", "GONG", "GOOD", "GOOF", "GORE", "GORY", "GOWN",
    "GRAB", "GRAD", "GRAM", "GRAY", "GREW", "GRID", "GRIM", "GRIN", "GRIP", "GRIT", "GROW",
    "GRUB", "GULF", "GULL", "GULP", "GUMS", "GUNS", "GURU", "GUST", "GUTS", "GUYS", "GYRO",
    "HAIL", "HAIR", "HALE", "HALF", "HALL", "HALO", "HALT", "HAND", "HANG", "HANK", "HARD",
    "HARE", "HARK", "HARM", "HARP", "HART", "HASH", "HATE", "HATS", "HAUL", "HAVE", "HAWK",
    "HAZE", "HAZY", "HEAD", "HEAL", "HEAP", "HEAR", "HEAT", "HECK", "HEED", "HEEL", "HEIR",
    "HELD", "HELL", "HELM", "HELP", "HEMP", "HENS", "HERB", "HERD", "HERE", "HERO", "HERS",
    "HICK", "HIDE", "HIGH", "HIKE", "HILL", "HILT", "HIND", "HINT", "HIPS", "HIRE", "HISS",
    "HITS", "HIVE", "HOAX", "HOCK", "HOLD", "HOLE", "HOLY", "HOME", "HONE", "HONK", "HOOD",
    "HOOK", "HOOP", "HOOT", "HOPE", "HOPS", "HORN", "HOSE", "HOST", "HOUR", "HOVE", "HOWL",
    "HUBS", "HUES", "HUFF", "HUGE", "HUGS", "HULA", "HULK", "HULL", "HUMS", "HUNG", "HUNT",
    "HURL", "HURT", "HUSH", "HUSK", "HUTS", "HYMN", "ICED", "ICES", "ICON", "IDEA", "IDLE",
    "IDLY", "IDOL", "INCH", "INFO", "INKS", "INKY", "INNS", "INTO", "IONS", "IOTA", "IRIS",
    "IRON", "ISLE", "ITCH", "ITEM", "JABS", "JACK", "JADE", "JAIL", "JAMS", "JARS", "JAWS",
    "JAZZ", "JEAN", "JEEP", "JEER", "JELL", "JERK", "JEST", "JETS", "JIBE", "JIGS", "JILT",
    "JINX", "JOBS", "JOCK", "JOGS", "JOIN", "JOKE", "JOLT", "JOSH", "JOTS", "JOWL", "JOYS",
    "JUDO", "JUGS", "JULY", "JUMP", "JUNE", "JUNK", "JURY", "JUST", "JUTE", "KEEL", "KEEN",
    "KEEP", "KEPT", "KEYS", "KICK", "KIDS", "KILL", "KILN", "KILO", "KILT", "KIND", "KING",
    "KISS", "KITE", "KITS", "KNEE", "KNEW", "KNIT", "KNOB", "KNOT", "KNOW", "LABS", "LACE",
    "LACK", "LACY", "LADS", "LADY", "LAID", "LAIR", "LAKE", "LAMB", "LAME", "LAMP", "LAND",
    "LANE", "LANK", "LAPS", "LARD", "LARK", "LASH", "LASS", "LAST", "LATE", "LAUD", "LAVA",
    "LAWN", "LAWS", "LAYS", "LAZE", "LAZY", "LEAD", "LEAF", "LEAK", "LEAN", "LEAP", "LEFT",
    "LEGS", "LEND", "LENS", "LENT", "LESS", "LEST", "LETS", "LEVY", "LEWD", "LIAR", "LICE",
    "LICK", "LIDS", "LIED", "LIEN", "LIES", "LIFE", "LIFT", "LIKE", "LILY", "LIMB", "LIME",
    "LIMP", "LINE", "LINK", "LINT", "LION", "LIPS", "LISP", "LIST", "LIVE", "LOAD", "LOAF",
    "LOAM", "LOAN", "LOBE", "LOCH", "LOCK", "LODE", "LOFT", "LOGS", "LOIN", "LONE", "LONG",
    "LOOK", "LOOM", "LOOP", "LORE", "LOSE", "LOSS", "LOST", "LOTS", "LOUD", "LOVE", "LOWS",
    "LUCK", "LUMP", "LUNG", "LURE", "LURK", "LUSH", "LUST", "LUTE", "LYRE", "MACE", "MADE",
    "MAID", "MAIL", "MAIN", "MAKE", "MALE", "MALT", "MANE", "MANY", "MAPS", "MARE", "MARK",
    "MARS", "MASH", "MASK", "MASS", "MAST", "MATE", "MATH", "MATS", "MAUL", "MAZE", "MEAD",
    "MEAL", "MEAN", "MEAT", "MEED", "MEEK", "MEET", "MELT", "MEND", "MENU", "MEOW", "MERE",
    "MESH", "MESS", "METE", "MICE", "MILD", "MILE", "MILK", "MILL", "MIME", "MIND", "MINE",
    "MINI", "MINT", "MINX", "MIRE", "MIST", "MITE", "MOAN", "MOAT", "MOCK", "MODE", "MOLD",
    "MOLE", "MOLT", "MONK", "MOOD", "MOON", "MOOR", "MOOT", "MOPE", "MORE", "MOSS", "MOST",
    "MOTE", "MOTH", "MOVE", "MOWN", "MUCH", "MUDD", "MUDS", "MUFF", "MUGS", "MULE", "MULL",
    "MUSE", "MUSH", "MUSK", "MUST", "MUTE", "MYTH", "NAIL", "NAME", "NAVY", "NEAR", "NEAT",
    "NECK", "NEED", "NEON", "NEST", "NETS", "NEWS", "NEWT", "NEXT", "NICE", "NICK", "NIGH",
    "NINE", "NODE", "NODS", "NOEL", "NONE", "NOOK", "NOON", "NOPE", "NORM", "NOSE", "NOTE",
    "NOUN", "NOVA", "NUDE", "NUMB", "NUNS", "NUTS", "OAKS", "OARS", "OATH", "OATS", "OBEY",
    "ODOR", "OGRE", "OILS", "OILY", "OINT", "OKAY", "OMEN", "OMIT", "ONCE", "ONES", "ONLY",
    "ONTO", "ONUS", "OOZE", "OPAL", "OPEN", "ORAL", "ORBS", "ORCA", "ORES", "OUCH", "OURS",
    "OUST", "OVAL", "OVEN", "OVER", "OWED", "OWES", "OWLS", "OWNS", "OXEN", "PACE", "PACK",
    "PACT", "PAGE", "PAID", "PAIL", "PAIN", "PAIR", "PALE", "PALM", "PANE", "PANG", "PANS",
    "PANT", "PAPA", "PARK", "PART", "PASS", "PAST", "PATH", "PATS", "PEAK", "PEAL", "PEAR",
    "PEAS", "PEAT", "PECK", "PEEK", "PEEL", "PEEP", "PEER", "PELT", "PEND", "PENS", "PERK",
    "PEST", "PETS", "PIED", "PIER", "PIES", "PIGS", "PIKE", "PILE", "PILL", "PINE", "PING",
    "PINK", "PINS", "PINT", "PIPE", "PITS", "PITY", "PLAN", "PLAY", "PLEA", "PLED", "PLOT",
    "PLOW", "PLUG", "PLUM", "PLUS", "POEM", "POET", "POKE", "POLE", "POLL", "POND", "PONY",
    "POOL", "POOR", "POPE", "POPS", "PORE", "PORK", "PORT", "POSE", "POST", "POTS", "POUR",
    "POUT", "PRAY", "PREY", "PRIG", "PRIM", "PROD", "PROP", "PROS", "PROW", "PUFF", "PULL",
    "PULP", "PUMP", "PUNS", "PUPS", "PURE", "PURR", "PUSH", "PUTT", "PUTS", "QUAY", "QUIT",
    "QUIZ", "RACE", "RACK", "RAFT", "RAGE", "RAGS", "RAID", "RAIL", "RAIN", "RAKE", "RAMP",
    "RAMS", "RANG", "RANK", "RANT", "RARE", "RASH", "RATE", "RATS", "RAVE", "RAYS", "RAZE",
    "READ", "REAL", "REAP", "REAR", "REED", "REEF", "REEK", "REEL", "REIN", "RELY", "RENT",
    "REST", "RIBS", "RICE", "RICH", "RIDE", "RIFE", "RIFT", "RIMS", "RING", "RINK", "RIPE",
    "RIPS", "RISE", "RISK", "RITE", "ROAD", "ROAM", "ROAR", "ROBE", "ROBS", "ROCK", "RODE",
    "RODS", "ROIL", "ROLE", "ROLL", "ROOF", "ROOM", "ROOT", "ROPE", "ROSE", "ROSY", "ROTE",
    "ROTS", "ROUT", "ROVE", "ROWS", "RUBE", "RUBS", "RUBY", "RUDE", "RUFF", "RUGS", "RUIN",
    "RULE", "RUMP", "RUNS", "RUNT", "RUSE", "RUSH", "RUST", "RUTS", "SACK", "SAFE", "SAGA",
    "SAGE", "SAID", "SAIL", "SAKE", "SALE", "SALT", "SAME", "SAND", "SANE", "SANG", "SANK",
    "SANS", "SAPS", "SASH", "SAVE", "SAWS", "SAYS", "SCAB", "SCAM", "SCAN", "SCAR", "SEAL",
    "SEAM", "SEAR", "SEAS", "SEAT", "SEED", "SEEK", "SEEM", "SEEN", "SEEP", "SEER", "SEES",
    "SELF", "SELL", "SEND", "SENT", "SETS", "SEWN", "SEWS", "SHED", "SHIN", "SHIP", "SHOE",
    "SHOP", "SHOT", "SHOW", "SHUN", "SHUT", "SICK", "SIDE", "SIFT", "SIGH", "SIGN", "SILK",
    "SILL", "SILO", "SILT", "SINE", "SING", "SINK", "SINS", "SIRE", "SITE", "SITS", "SIZE",
    "SKEW", "SKID", "SKIM", "SKIN", "SKIP", "SKIT", "SLAB", "SLAM", "SLAP", "SLAT", "SLAW",
    "SLED", "SLEW", "SLID", "SLIM", "SLIP", "SLIT", "SLOG", "SLOP", "SLOT", "SLOW", "SLUG",
    "SLUM", "SLUR", "SMOG", "SNAP", "SNIP", "SNOW", "SNUB", "SNUG", "SOAK", "SOAP", "SOAR",
    "SOCK", "SODA", "SOFA", "SOFT", "SOIL", "SOLD", "SOLE", "SOLO", "SOME", "SONG", "SONS",
    "SOON", "SOOT", "SORE", "SORT", "SOUL", "SOUP", "SOUR", "SOWN", "SOWS", "SPAM", "SPAN",
    "SPAR", "SPAT", "SPEW", "SPIN", "SPIT", "SPOT", "SPRY", "SPUD", "SPUR", "STAG", "STAR",
    "STAY", "STEM", "STEP", "STEW", "STIR", "STOP", "STUB", "STUD", "SUCH", "SUCK", "SUIT",
    "SULK", "SUNG", "SUNK", "SURE", "SURF", "SWAN", "SWAP", "SWAT", "SWAY", "SWIM", "TACK",
    "TACT", "TAIL", "TAKE", "TALE", "TALK", "TALL", "TAME", "TANK", "TAPE", "TAPS", "TART",
    "TASK", "TEAL", "TEAM", "TEAR", "TEAS", "TEAT", "TEEM", "TEEN", "TELL", "TENT", "TERM",
    "TEST", "TEXT", "THAT", "THEM", "THEN", "THEY", "THIN", "THIS", "THOU", "THUD", "THUG",
    "TICK", "TIDE", "TIDY", "TIED", "TIER", "TIES", "TILE", "TILL", "TILT", "TIME", "TINS",
    "TINT", "TINY", "TIPS", "TIRE", "TOAD", "TOED", "TOES", "TOIL", "TOLD", "TOLL", "TOMB",
    "TOME", "TONE", "TONS", "TOOK", "TOOL", "TOOT", "TOPS", "TORE", "TORN", "TOSS", "TOUR",
    "TOWN", "TOYS", "TRAP", "TRAY", "TREE", "TREK", "TRIM", "TRIO", "TRIP", "TROD", "TROT",
    "TRUE", "TUBE", "TUBS", "TUCK", "TUFT", "TUNA", "TUNE", "TURF", "TURN", "TUSK", "TWIG",
    "TWIN", "TYPE", "TYPO", "UNIT", "UNTO", "UPON", "URGE", "USED", "USER", "USES", "VAIN",
    "VALE", "VAMP", "VANE", "VANS", "VARY", "VASE", "VAST", "VEAL", "VEIL", "VEIN", "VENT",
    "VERB", "VERY", "VEST", "VETO", "VIAL", "VICE", "VIEW", "VINE", "VISA", "VISE", "VOID",
    "VOLT", "VOTE", "VOWS", "WADE", "WAGE", "WAIL", "WAIT", "WAKE", "WALK", "WALL", "WAND",
    "WANT", "WARD", "WARM", "WARN", "WARS", "WART", "WASH", "WASP", "WAVE", "WAVY", "WAYS",
    "WEAK", "WEAN", "WEAR", "WEBS", "WEED", "WEEK", "WEEP", "WELD", "WELL", "WENT", "WEPT",
    "WERE", "WEST", "WETS", "WHAT", "WHEAT", "WHEW", "WHIM", "WHIP", "WHIZ", "WHOA", "WHOM",
    "WIDE", "WIFE", "WILD", "WILL", "WILT", "WIND", "WINE", "WING", "WINK", "WINS", "WIPE",
    "WIRE", "WIRY", "WISE", "WISH", "WISP", "WITH", "WOLF", "WOMB", "WONT", "WOOD", "WOOF",
    "WOOL", "WORD", "WORE", "WORK", "WORM", "WORN", "WRAP", "WREN", "YARD", "YARN", "YAWN",
    "YEAR", "YELL", "YOGA", "YOKE", "YOLK", "YOUR", "ZEAL", "ZERO", "ZINC", "ZONE"
};

const size_t LexiconData::VOCABULARY_LIST_4_SIZE = sizeof(VOCABULARY_LIST_4) / sizeof(VOCABULARY_LIST_4[0]);

const char* const LexiconData::VOCABULARY_LIST_5[] = {
    "ABOUT", "ABOVE", "ABUSE", "ACTOR", "ACUTE", "ADAPT", "ADMIT", "ADOPT", "ADULT", "AFTER",
    "AGAIN", "AGENT", "AGREE", "AHEAD", "ALARM", "ALBUM", "ALERT", "ALIKE", "ALIVE", "ALLOW",
    "ALONE", "ALONG", "ALTER", "AMONG", "ANGER", "ANGLE", "ANGRY", "APART", "APPLE", "APPLY",
    "ARENA", "ARGUE", "ARISE", "ARMED", "ARMOR", "ARROW", "ASIDE", "ASSET", "AUDIO", "AUDIT",
    "AVOID", "AWAIT", "AWAKE", "AWARD", "AWARE", "BADLY", "BAKER", "BASES", "BASIC", "BASIS",
    "BEACH", "BEGAN", "BEGIN", "BEGUN", "BEING", "BELOW", "BENCH", "BILLY", "BIRTH", "BLACK",
    "BLAME", "BLIND", "BLOCK", "BLOOD", "BOARD", "BOAST", "BOOST", "BOOTH", "BOUND", "BRAIN",
    "BRAND", "BRASS", "BRAVE", "BREAD", "BREAK", "BREED", "BRIEF", "BRING", "BROAD", "BROKE",
    "BROWN", "BUILD", "BUILT", "BUYER", "CABLE", "CALIF", "CANDY", "CARRY", "CATCH", "CAUSE",
    "CHAIN", "CHAIR", "CHAMP", "CHART", "CHASE", "CHEAP", "CHECK", "CHEST", "CHIEF", "CHILD",
    "CHINA", "CHOSE", "CIVIL", "CLAIM", "CLASS", "CLEAN", "CLEAR", "CLICK", "CLOCK", "CLOSE",
    "COACH", "COAST", "COULD", "COUNT", "COURT", "COVER", "CRAFT", "CRASH", "CREAM", "CRIME",
    "CROSS", "CROWD", "CROWN", "CUBIC", "CYBER", "CYCLE", "DAILY", "DANCE", "DATED", "DEALT",
    "DEATH", "DEBUT", "DELAY", "DELTA", "DEPTH", "DOING", "DOUBT", "DOZEN", "DRAFT", "DRAMA",
    "DRAWN", "DREAM", "DRESS", "DRIFT", "DRINK", "DRIVE", "DROVE", "DYING", "EAGER", "EAGLE",
    "EARLY", "EARTH", "EIGHT", "ELITE", "EMPTY", "ENEMY", "ENJOY", "ENTER", "ENTRY", "EQUAL",
    "ERROR", "EVENT", "EVERY", "EXACT", "EXIST", "EXTRA", "FAITH", "FALSE", "FAULT", "FIBER",
    "FIELD", "FIFTH", "FIFTY", "FIGHT", "FINAL", "FIRST", "FIXED", "FLASH", "FLEET", "FLOOR",
    "FLUID", "FOCUS", "FORCE", "FORTH", "FORTY", "FORUM", "FOUND", "FRAME", "FRANK", "FRAUD",
    "FRESH", "FRONT", "FRUIT", "FULLY", "FUNNY", "GIANT", "GIVEN", "GLASS", "GLOBE", "GOING",
    "GRACE", "GRADE", "GRAND", "GRANT", "GRASS", "GREAT", "GREEN", "GROSS", "GROUP", "GROWN",
    "GUARD", "GUESS", "GUEST", "GUIDE", "HAPPY", "HARRY", "HASTE", "HEART", "HEAVY", "HENCE",
    "HENRY", "HORSE", "HOTEL", "HOUSE", "HUMAN", "IDEAL", "IMAGE", "INDEX", "INNER", "INPUT",
    "ISSUE", "JAPAN", "JIMMY", "JOINT", "JONES", "JUDGE", "KNOWN", "LABEL", "LARGE", "LASER",
    "LATER", "LAUGH", "LAYER", "LEARN", "LEASE", "LEAST", "LEAVE", "LEGAL", "LEVEL", "LEWIS",
    "LIGHT", "LIMIT", "LINKS", "LIVES", "LOCAL", "LOGIC", "LOOSE", "LOWER", "LUCKY", "LUNAR",
    "LUNCH", "MAGIC", "MAJOR", "MAKER", "MARCH", "MATCH", "MAYOR", "MEANT", "MEDIA", "METAL",
    "MIGHT", "MINOR", "MINUS", "MIXED", "MODEL", "MONEY", "MONTH", "MORAL", "MOTOR", "MOUNT",
    "MOUSE", "MOUTH", "MOVIE", "MUSIC", "NEEDS", "NEVER", "NEWLY", "NIGHT", "NINJA", "NOISE",
    "NORTH", "NOTED", "NOVEL", "NURSE", "OCCUR", "OCEAN", "OFFER", "OFTEN", "ORDER", "OTHER",
    "OUGHT", "PAINT", "PANEL", "PAPER", "PARTY", "PEACE", "PETER", "PHASE", "PHONE", "PHOTO",
    "PIECE", "PILOT", "PIXEL", "PITCH", "PLACE", "PLAIN", "PLANE", "PLANT", "PLATE", "POINT",
    "POUND", "POWER", "PRESS", "PRICE", "PRIDE", "PRIME", "PRINT", "PRISM", "PRIOR", "PRIZE",
    "PROOF", "PROUD", "PROVE", "PULSE", "QUEEN", "QUICK", "QUIET", "QUITE", "RADIO", "RAISE",
    "RANGE", "RAPID", "RATIO", "RAVEN", "REACH", "READY", "REFER", "RIGHT", "RIVAL", "RIVER",
    "ROBIN", "ROBOT", "ROUND", "ROUTE", "ROYAL", "RURAL", "SCALE", "SCENE", "SCOPE", "SCORE",
    "SENSE", "SERVE", "SETUP", "SEVEN", "SHALL", "SHAPE", "SHARE", "SHARP", "SHEET", "SHELF",
    "SHELL", "SHIFT", "SHINE", "SHIRT", "SHOCK", "SHOOT", "SHORT", "SHOWN", "SIGHT", "SINCE",
    "SIXTH", "SIXTY", "SIZED", "SKILL", "SLEEP", "SLIDE", "SMALL", "SMART", "SMILE", "SMOKE",
    "SOLID", "SOLVE", "SORRY", "SOUND", "SOUTH", "SPACE", "SPARK", "SPEAK", "SPEED", "SPEND",
    "SPENT", "SPLIT", "SPOKE", "SPORT", "STAFF", "STAGE", "STAKE", "STAND", "START", "STATE",
    "STEAM", "STEEL", "STICK", "STILL", "STOCK", "STONE", "STOOD", "STORM", "STORY", "STRIP",
    "STUCK", "STUDY", "STUFF", "STYLE", "SUGAR", "SUITE", "SUPER", "SWEET", "SWIFT", "SWORD",
    "TABLE", "TAKEN", "TASTE", "TAXES", "TEACH", "TEETH", "TERRY", "TEXAS", "THANK", "THEFT",
    "THEIR", "THEME", "THERE", "THESE", "THICK", "THING", "THINK", "THIRD", "THOSE", "THREE",
    "THREW", "THROW", "TIGER", "TIGHT", "TIMES", "TIRED", "TITLE", "TODAY", "TOPIC", "TOTAL",
    "TOUCH", "TOUGH", "TOWER", "TRACK", "TRADE", "TRAIN", "TREAT", "TREND", "TRIAL", "TRIED",
    "TRIES", "TRUCK", "TRULY", "TRUST", "TRUTH", "TWICE", "UNDER", "UNDUE", "UNION", "UNITY",
    "UNTIL", "UPPER", "UPSET", "URBAN", "USAGE", "USUAL", "VALID", "VALUE", "VIDEO", "VIPER",
    "VIRUS", "VISIT", "VITAL", "VOICE", "WASTE", "WATCH", "WATER", "WHEEL", "WHERE", "WHICH",
    "WHILE", "WHITE", "WHOLE", "WHOSE", "WOMAN", "WOMEN", "WORLD", "WORRY", "WORSE", "WORST",
    "WORTH", "WOULD", "WOUND", "WRITE", "WRONG", "WROTE", "YIELD", "YOUNG", "YOUTH"
};

const size_t LexiconData::VOCABULARY_LIST_5_SIZE = sizeof(VOCABULARY_LIST_5) / sizeof(VOCABULARY_LIST_5[0]);

const char* const LexiconData::VOCABULARY_LIST_6[] = {
    "ACTION", "ACTIVE", "ACTUAL", "ADVICE", "AFFECT", "AFFORD", "AFRAID", "AGENCY", "AGENDA",
    "ALMOST", "ALWAYS", "AMOUNT", "ANIMAL", "ANNUAL", "ANSWER", "ANYONE", "ANYWAY", "APPEAL",
    "APPEAR", "AROUND", "ARRIVE", "ARTIST", "ASPECT", "ASSUME", "ATTACK", "ATTEND", "AUGUST",
    "AUTHOR", "AVENUE", "BARELY", "BATTLE", "BEAUTY", "BECOME", "BEFORE", "BEHIND", "BELIEF",
    "BELONG", "BESIDE", "BETTER", "BEYOND", "BORDER", "BORROW", "BOTHER", "BOTTLE", "BOTTOM",
    "BOUGHT", "BRANCH", "BREATH", "BRIDGE", "BRIGHT", "BROKEN", "BUDGET", "BURDEN", "BUREAU",
    "BUTTON", "CAMERA", "CANCER", "CANDLE", "CANNOT", "CARBON", "CAREER", "CASTLE", "CASUAL",
    "CAUGHT", "CENTER", "CHANCE", "CHANGE", "CHARGE", "CHOICE", "CHOOSE", "CHURCH", "CIRCLE",
    "CLIENT", "CLOSED", "CLOSER", "COFFEE", "COLUMN", "COMBAT", "COMING", "COMMON", "COMPLY",
    "COPPER", "CORNER", "COSTLY", "COUNTY", "COUPLE", "COURSE", "COUSIN", "CREDIT", "CRISIS",
    "CUSTOM", "DAMAGE", "DANGER", "DEALER", "DECADE", "DECIDE", "DEFEAT", "DEFEND", "DEFINE",
    "DEGREE", "DEPUTY", "DESERT", "DESIGN", "DESIRE", "DETAIL", "DETECT", "DEVICE", "DIFFER",
    "DINNER", "DIRECT", "DOCTOR", "DOLLAR", "DOMAIN", "DOUBLE", "DRIVEN", "DRIVER", "DURING",
    "EASILY", "EATING", "EDITOR", "EFFECT", "EFFORT", "EIGHTH", "EITHER", "ELEVEN", "EMERGE",
    "EMPIRE", "EMPLOY", "ENABLE", "ENDING", "ENERGY", "ENGINE", "ENOUGH", "ENSURE", "ENTIRE",
    "ENTITY", "EQUITY", "ESCAPE", "ESTATE", "ETHICS", "EXCEED", "EXCEPT", "EXCUSE", "EXPAND",
    "EXPECT", "EXPERT", "EXPORT", "EXTEND", "EXTENT", "FABRIC", "FACTOR", "FAILED", "FAIRLY",
    "FAMILY", "FAMOUS", "FATHER", "FELLOW", "FEMALE", "FIGURE", "FILING", "FINGER", "FINISH",
    "FISCAL", "FLIGHT", "FLOWER", "FLYING", "FOLLOW", "FORBID", "FORCED", "FOREST", "FORGET",
    "FORMAT", "FORMER", "FOSTER", "FOUGHT", "FOURTH", "FREEZE", "FRIEND", "FUTURE", "GALAXY",
    "GARDEN", "GATHER", "GENDER", "GENTLE", "GERMAN", "GLOBAL", "GOLDEN", "GROUND", "GROWTH",
    "GUILTY", "HANDED", "HANDLE", "HAPPEN", "HARBOR", "HARDLY", "HEADED", "HEALTH", "HEARING",
    "HEAVEN", "HEIGHT", "HELPED", "HERSELF", "HIDDEN", "HOLDER", "HONEST", "IMPACT", "IMPORT",
    "INCOME", "INDEED", "INJURY", "INSIDE", "INTEND", "INVEST", "ISLAND", "ITSELF", "JACKET",
    "JUNIOR", "KILLED", "KNIGHT", "LABOR", "LACKED", "LADDER", "LADIES", "LANCER", "LANDED",
    "LAPTOP", "LARGELY", "LATEST", "LATTER", "LAUGH", "LAUNCH", "LAWYER", "LEADER", "LEAGUE",
    "LEAVES", "LEGACY", "LEGEND", "LENDER", "LENGTH", "LESSON", "LETTER", "LIGHTS", "LIKELY",
    "LINKED", "LIQUID", "LISTEN", "LITTLE", "LIVING", "LOADED", "LOCATE", "LOCKED", "LONGER",
    "LOOKED", "LOSING", "LOVELY", "LOVING", "LUMBER", "LUXURY", "MAGNET", "MAINLY", "MAKING",
    "MANAGE", "MANNER", "MANUAL", "MARGIN", "MARINE", "MARKET", "MASTER", "MATTER", "MATURE",
    "MEDIUM", "MEMBER", "MEMORY", "MENTAL", "MERELY", "MERGER", "METHOD", "MIDDLE", "MILLER",
    "MINING", "MINUTE", "MIRROR", "MOBILE", "MODERN", "MODIFY", "MODULE", "MOMENT", "MORTAL",
    "MOSTLY", "MOTHER", "MOTION", "MOVING", "MURDER", "MUSEUM", "MUTUAL", "MYSELF", "NATION",
    "NATIVE", "NATURE", "NEARBY", "NEEDLE", "NEPHEW", "NERVOUS", "NEWEST", "NEWSPAPER", "NIGHTS",
    "NOBODY", "NORMAL", "NOTICE", "NOTION", "NUMBER", "OBJECT", "OBTAIN", "OFFICE", "OFFSET",
    "ONLINE", "OPENED", "OPTION", "ORANGE", "ORIGIN", "OUTPUT", "PACKED", "PALACE", "PARENT",
    "PARTLY", "PATENT", "PEOPLE", "PERIOD", "PERMIT", "PERSON", "PHRASE", "PICKED", "PICTURE",
    "PLANET", "PLAYER", "PLEASE", "PLENTY", "POCKET", "POETRY", "POLICE", "POLICY", "POORLY",
    "PRAYER", "PREFER", "PRETTY", "PRINCE", "PRISON", "PROFIT", "PROPER", "PROVE", "PUBLIC",
    "PURSUE", "PUZZLE", "RABBIT", "RADICAL", "RANDOM", "RARELY", "RATHER", "RATING", "READER",
    "REALLY", "REASON", "RECALL", "RECENT", "RECORD", "REDUCE", "REFORM", "REGARD", "REGIME",
    "REGION", "RELATE", "RELIEF", "REMAIN", "REMOTE", "REMOVE", "REPAIR", "REPEAT", "REPLACE",
    "REPORT", "RESCUE", "RESIGN", "RESIST", "RESORT", "RESULT", "RETAIL", "RETAIN", "RETURN",
    "REVEAL", "REVIEW", "REWARD", "RISING", "ROBUST", "ROCKET", "ROUTINE", "RUNNER", "SAFETY",
    "SALARY", "SAMPLE", "SAVING", "SCHEME", "SCHOOL", "SCREEN", "SCRIPT", "SEARCH", "SEASON",
    "SECOND", "SECRET", "SECTOR", "SECURE", "SEEING", "SELECT", "SELLER", "SENIOR", "SERIES",
    "SERIOUS", "SERVER", "SETTLE", "SEVERE", "SHADOW", "SHARED", "SHIELD", "SHOULD", "SILENT",
    "SILVER", "SIMPLE", "SIMPLY", "SINGLE", "SISTER", "SLIGHT", "SMOOTH", "SOCIAL", "SOLELY",
    "SOUGHT", "SOURCE", "SOVIET", "SPEECH", "SPIRIT", "SPREAD", "SPRING", "SQUARE", "STABLE",
    "STATUS", "STEADY", "STOLEN", "STRAIN", "STREAM", "STREET", "STRESS", "STRICT", "STRIKE",
    "STRING", "STRONG", "STRUCK", "STUDIO", "SUBMIT", "SUDDEN", "SUFFER", "SUMMER", "SUMMIT",
    "SUPPLY", "SURELY", "SURVEY", "SWITCH", "SYMBOL", "SYSTEM", "TAKING", "TALENT", "TARGET",
    "TAUGHT", "TENANT", "TENDER", "TENNIS", "TERMS", "TERROR", "THANKS", "THEORY", "THIRTY",
    "THREAT", "TIMING", "TISSUE", "TITLE", "TODAY", "TONIGHT", "TOPIC", "TOWARD", "TRAGIC",
    "TRAVEL", "TREATY", "TRENDY", "TRIAL", "TRIPLE", "TROPHY", "TRUCKS", "TRYING", "TUNNEL",
    "TURNING", "TWELVE", "TWENTY", "UNABLE", "UNIQUE", "UNITED", "UNLESS", "UNLIKE", "UPDATE",
    "USEFUL", "VALLEY", "VALUED", "VARIED", "VICTIM", "VICTOR", "VIEWER", "VIOLET", "VIRTUE",
    "VISION", "VISUAL", "VOLUME", "WALKER", "WALLET", "WANTED", "WARMTH", "WEAKEN", "WEALTH",
    "WEAPON", "WEEKLY", "WEIGHT", "WINDOW", "WINNER", "WINTER", "WISDOM", "WONDER", "WOODEN",
    "WORKER", "WRITER", "YELLOW", "ZEALOT"
};

const size_t LexiconData::VOCABULARY_LIST_6_SIZE = sizeof(VOCABULARY_LIST_6) / sizeof(VOCABULARY_LIST_6[0]);

const LexiconEntry* LexiconData::findEntry(const std::string& rawWord) {
    std::string clean = "";
    for (char c : rawWord) if (std::isalpha(static_cast<unsigned char>(c))) clean += static_cast<char>(std::toupper(c));

    for (size_t i = 0; i < CORE_DICTIONARY_SIZE; ++i) {
        if (clean == CORE_DICTIONARY[i].word) {
            return &CORE_DICTIONARY[i];
        }
    }
    return nullptr;
}

std::vector<std::string> LexiconData::getWordsByLength(int length) {
    std::vector<std::string> res;
    if (length == 3) {
        for (size_t i = 0; i < VOCABULARY_LIST_3_SIZE; ++i) res.push_back(VOCABULARY_LIST_3[i]);
    } else if (length == 4) {
        for (size_t i = 0; i < VOCABULARY_LIST_4_SIZE; ++i) res.push_back(VOCABULARY_LIST_4[i]);
    } else if (length == 5) {
        for (size_t i = 0; i < VOCABULARY_LIST_5_SIZE; ++i) res.push_back(VOCABULARY_LIST_5[i]);
    } else if (length == 6) {
        for (size_t i = 0; i < VOCABULARY_LIST_6_SIZE; ++i) res.push_back(VOCABULARY_LIST_6[i]);
    }
    return res;
}

std::vector<std::string> LexiconData::getWordsByDifficulty(const std::string& diff) {
    std::string cleanDiff = diff;
    for (char& c : cleanDiff) c = static_cast<char>(std::toupper(c));

    std::vector<std::string> res;
    for (size_t i = 0; i < CORE_DICTIONARY_SIZE; ++i) {
        if (cleanDiff == CORE_DICTIONARY[i].difficulty) {
            res.push_back(CORE_DICTIONARY[i].word);
        }
    }
    return res;
}

} // namespace WordRush
