// ============================================================================
// WordRush Comprehensive English Lexicon & Anagram Word Bank
// Contains thousands of verified 3, 4, 5, and 6-letter English vocabulary words
// Ensures every meaningful anagram and word combination is recognized instantly!
// ============================================================================

export const COMMON_VOCABULARY = [
  // 3-Letter Words
  "ACT", "ADD", "AGE", "AGO", "AID", "AIM", "AIR", "ALL", "AND", "ANT", "ANY", "APE",
  "ARC", "ARM", "ART", "ASH", "ASK", "ATE", "AWE", "AXE", "BAD", "BAG", "BAN", "BAR",
  "BAT", "BAY", "BED", "BEE", "BEG", "BET", "BID", "BIG", "BIN", "BIT", "BOB", "BOW",
  "BOX", "BOY", "BUG", "BUS", "BUT", "BUY", "CAB", "CAN", "CAP", "CAR", "CAT", "COW",
  "CRY", "CUP", "CUT", "DAD", "DAM", "DAY", "DEN", "DEW", "DID", "DIE", "DIG", "DIM",
  "DIP", "DOG", "DOT", "DRY", "DUE", "DUG", "DYE", "EAR", "EAT", "EGG", "EGO", "ELF",
  "ELM", "END", "ERA", "EVE", "EYE", "FAN", "FAR", "FAT", "FED", "FEE", "FEW", "FIG",
  "FIT", "FIX", "FLY", "FOE", "FOG", "FOR", "FOX", "FRY", "FUN", "FUR", "GAP", "GAS",
  "GEL", "GEM", "GET", "GIG", "GLAD", "GOD", "GOT", "GUM", "GUN", "GUT", "GUY", "GYM",
  "HAD", "HAM", "HAS", "HAT", "HAY", "HEN", "HER", "HID", "HIM", "HIP", "HIS", "HIT",
  "HOP", "HOT", "HOW", "HUB", "HUG", "HUM", "HUT", "ICE", "ILL", "INK", "INN", "ION",
  "IRE", "IVY", "JAM", "JAR", "JAW", "JAY", "JET", "JIG", "JOB", "JOG", "JOY", "JUG",
  "KEY", "KID", "KIN", "KIT", "LAB", "LAD", "LAP", "LAW", "LAY", "LED", "LEG", "LET",
  "LID", "LIE", "LIP", "LIT", "LOG", "LOT", "LOW", "MAD", "MAN", "MAP", "MAT", "MAY",
  "MEN", "MET", "MID", "MIX", "MOM", "MOP", "MUD", "MUG", "NET", "NEW", "NIL", "NOD",
  "NOT", "NOW", "NUT", "OAK", "OAR", "ODD", "OFF", "OFT", "OIL", "OLD", "ONE", "OPT",
  "ORB", "OUR", "OUT", "OWL", "OWN", "PAD", "PAN", "PAR", "PAT", "PAW", "PAY", "PEA",
  "PEG", "PEN", "PET", "PIE", "PIG", "PIN", "PIT", "PLY", "POD", "POP", "POT", "PRO",
  "PUB", "PUN", "PUP", "PUT", "RAG", "RAM", "RAN", "RAP", "RAT", "RAW", "RAY", "RED",
  "RIB", "RID", "RIG", "RIM", "RIP", "ROB", "ROD", "ROT", "ROW", "RUB", "RUG", "RUN",
  "RUT", "RYE", "SAD", "SAG", "SAP", "SAT", "SAW", "SAY", "SEA", "SEE", "SET", "SEW",
  "SHE", "SHY", "SIN", "SIP", "SIR", "SIT", "SKI", "SKY", "SLY", "SOB", "SON", "SOW",
  "SOY", "SPA", "SPY", "SUM", "SUN", "TAB", "TAG", "TAN", "TAP", "TAR", "TAX", "TEA",
  "TED", "TEE", "TEN", "THE", "THY", "TIE", "TIN", "TIP", "TOE", "TON", "TOO", "TOP",
  "TOW", "TOY", "TRY", "TUB", "TUG", "TWO", "URN", "USE", "VAN", "VAT", "VET", "VIA",
  "VOW", "WAG", "WAR", "WAS", "WAY", "WEB", "WED", "WET", "WHO", "WHY", "WIG", "WIN",
  "WIT", "WOE", "WON", "YAK", "YAM", "YAP", "YAW", "YEA", "YES", "YET", "YOU", "ZIP", "ZOO",

  // 4-Letter Words (Comprehensive - includes TIED, DIET, EDIT, TIDE, etc.)
  "ACED", "ACES", "ACHE", "ACID", "ACRE", "ACTS", "AGED", "AGES", "AIDE", "AIDS", "AIMS",
  "AIRS", "AJAR", "ALLY", "ALMS", "ALOE", "ALPS", "ALSO", "ALTO", "AMEN", "AMID", "AMPS",
  "ANEW", "ANTS", "APES", "APEX", "APPS", "AQUA", "ARCH", "AREA", "ARID", "ARMS", "ARMY",
  "ARTS", "ASHY", "ASKS", "ATOM", "AUNT", "AURA", "AUTO", "AVID", "AVOW", "AWAY", "AXES",
  "AXIS", "AXLE", "BABE", "BABY", "BACK", "BADE", "BAIL", "BAIT", "BAKE", "BALD", "BALE",
  "BALL", "BALM", "BAND", "BANE", "BANG", "BANK", "BARE", "BARK", "BARN", "BARS", "BASE",
  "BASH", "BASK", "BASS", "BATE", "BATH", "BATS", "BEAM", "BEAN", "BEAR", "BEAT", "BEAU",
  "BEEF", "BEEN", "BEER", "BEES", "BEET", "BEGS", "BELL", "BELT", "BEND", "BENT", "BEST",
  "BETA", "BETS", "BIAS", "BIDE", "BIDS", "BIKE", "BILE", "BILL", "BIND", "BINS", "BIRD",
  "BITE", "BITS", "BLAB", "BLED", "BLEW", "BLIP", "BLOB", "BLOT", "BLOW", "BLUE", "BLUR",
  "BOAR", "BOAT", "BOBS", "BODE", "BODY", "BOIL", "BOLD", "BOLE", "BOLL", "BOLT", "BOMB",
  "BOND", "BONE", "BONY", "BOOK", "BOOM", "BOON", "BOOT", "BORE", "BORN", "BOSS", "BOTH",
  "BOUT", "BOWL", "BOWS", "BOYS", "BRAG", "BRAN", "BRAS", "BRAT", "BRAY", "BRED", "BREW",
  "BRIM", "BROW", "BUCK", "BUDS", "BUFF", "BUGS", "BULB", "BULK", "BULL", "BUMP", "BUMS",
  "BUNT", "BUOY", "BURN", "BURY", "BUSH", "BUSY", "BUTE", "BUTS", "BUTT", "BUYS", "BUZZ",
  "CAFE", "CAGE", "CAKE", "CALF", "CALL", "CALM", "CAME", "CAMP", "CANE", "CANS", "CAPE",
  "CAPS", "CARD", "CARE", "CARP", "CARS", "CART", "CASE", "CASH", "CASK", "CAST", "CATS",
  "CAVE", "CEDE", "CELL", "CENT", "CHAD", "CHAP", "CHAT", "CHEF", "CHEW", "CHIN", "CHIP",
  "CHOP", "CHUM", "CITE", "CITY", "CLAD", "CLAM", "CLAN", "CLAP", "CLAW", "CLAY", "CLIP",
  "CLOD", "CLOG", "CLOP", "CLOT", "CLUB", "CLUE", "COAL", "COAT", "COAX", "COCK", "CODE",
  "COIL", "COIN", "COKE", "COLD", "COLT", "COMA", "COMB", "COME", "CONE", "COOK", "COOL",
  "COOP", "COPE", "COPS", "COPY", "CORD", "CORE", "CORK", "CORN", "COST", "COSY", "COTS",
  "COUP", "COVE", "COWL", "COWS", "COZY", "CRAB", "CRAG", "CRAM", "CRAN", "CRAP", "CREW",
  "CRIB", "CROP", "CROW", "CRUB", "CRUD", "CRUX", "CUBE", "CUBS", "CUED", "CUES", "CUFF",
  "CULL", "CULT", "CUPS", "CURB", "CURD", "CURE", "CURL", "CURT", "CUSP", "CUTE", "CUTS",
  "CYST", "CZAR", "DADO", "DAIS", "DALE", "DAME", "DAMP", "DAMS", "DANK", "DARE", "DARK",
  "DART", "DASH", "DATA", "DATE", "DAWN", "DAYS", "DAZE", "DEAD", "DEAF", "DEAL", "DEAN",
  "DEAR", "DEBT", "DECK", "DEED", "DEEM", "DEEP", "DEER", "DEFT", "DEFY", "DELI", "DELL",
  "DENT", "DENY", "DESK", "DIAL", "DICE", "DIED", "DIES", "DIET", "DIGS", "DIME", "DINE",
  "DING", "DINT", "DIPS", "DIRE", "DIRT", "DISC", "DISH", "DISK", "DIVE", "DOCK", "DOCS",
  "DODO", "DOER", "DOES", "DOGS", "DOLE", "DOLL", "DOLT", "DOME", "DONE", "DOOM", "DOOR",
  "DOPE", "DOSE", "DOTE", "DOTH", "DOTS", "DOVE", "DOWN", "DRAB", "DRAG", "DRAM", "DRAW",
  "DREW", "DRIP", "DROP", "DRUB", "DRUG", "DRUM", "DUAL", "DUCK", "DUCT", "DUDE", "DUDS",
  "DUEL", "DUES", "DUET", "DUFF", "DUKE", "DULL", "DULY", "DUMB", "DUMP", "DUNE", "DUNG",
  "DUNK", "DUSK", "DUST", "DUTY", "DYAD", "DYED", "DYES", "EACH", "EARL", "EARN", "EARS",
  "EASE", "EAST", "EASY", "EATS", "ECHO", "EDDY", "EDGE", "EDGY", "EDIT", "EELS", "EGGS",
  "EGOS", "ELAN", "ELKS", "ELMS", "ELSE", "EMIR", "EMIT", "ENDS", "ENVY", "EPIC", "EPOS",
  "ERAS", "ERGO", "ERRS", "ETCH", "EVEN", "EVER", "EVES", "EVIL", "EXAM", "EXIT", "EXPO",
  "EYED", "EYES", "FACE", "FACT", "FADE", "FAIL", "FAIR", "FAKE", "FALL", "FAME", "FANG",
  "FANS", "FARE", "FARM", "FAST", "FATE", "FATS", "FAWN", "FEAR", "FEAT", "FEED", "FEEL",
  "FEES", "FEET", "FELL", "FELT", "FEND", "FERN", "FEST", "FETE", "FEUD", "FIAT", "FIEF",
  "FIGS", "FILE", "FILL", "FILM", "FIND", "FINE", "FINS", "FIRE", "FIRM", "FISH", "FIST",
  "FITS", "FIVE", "FLAG", "FLAK", "FLAP", "FLAT", "FLAW", "FLAX", "FLEA", "FLED", "FLEE",
  "FLEW", "FLEX", "FLIP", "FLIT", "FLOE", "FLOG", "FLOP", "FLOW", "FLUE", "FOAL", "FOAM",
  "FOES", "FOIL", "FOLD", "FOLK", "FOND", "FONT", "FOOD", "FOOL", "FOOT", "FORD", "FORE",
  "FORK", "FORM", "FORT", "FOUL", "FOUR", "FOWL", "FOXY", "FRAY", "FREE", "FRET", "FROG",
  "FROM", "FUEL", "FULL", "FUME", "FUND", "FURS", "FURY", "FUSE", "FUSS", "FUZZ", "GAGE",
  "GAIN", "GAIT", "GALA", "GALE", "GALL", "GAME", "GANG", "GAOL", "GAPE", "GAPS", "GARB",
  "GASH", "GASP", "GATE", "GAVE", "GAZE", "GEAR", "GEEK", "GEMS", "GENE", "GENT", "GERM",
  "GETS", "GIFT", "GILD", "GILL", "GILT", "GIRD", "GIRL", "GIST", "GIVE", "GLAD", "GLEE",
  "GLEN", "GLIB", "GLIM", "GLOB", "GLOP", "GLOW", "GLUE", "GLUM", "GLUT", "GOAD", "GOAL",
  "GOAT", "GODS", "GOLD", "GOLF", "GONE", "GONG", "GOOD", "GOOF", "GORE", "GORY", "GOWN",
  "GRAB", "GRAD", "GRAM", "GRAY", "GREW", "GRID", "GRIM", "GRIN", "GRIP", "GRIT", "GROW",
  "GRUB", "GULF", "GULL", "GULP", "GUMS", "GUNS", "GURU", "GUST", "GUTS", "GUYS", "GYRO",
  "HAIL", "HAIR", "HALE", "HALF", "HALL", "HALO", "HALT", "HAND", "HANG", "HANK", "HARD",
  "HARE", "HARK", "HARM", "HARP", "HART", "HASH", "HATE", "HATS", "HAUL", "HAVE", "HAWK",
  "HAZE", "HAZY", "HEAD", "HEAL", "HEAP", "HEAR", "HEAT", "HECK", "HEED", "HEEL", "HEIR",
  "HELD", "HELL", "HELM", "HELP", "HEMP", "HENS", "HERB", "HERD", "HERE", "HERO", "HERS",
  "HICK", "HIDE", "HIGH", "HIKE", "HILL", "HILT", "HIND", "HINT", "HIPS", "HIRE", "HISS",
  "HITS", "HIVE", "HOAX", "HOCK", "HOLD", "HOLE", "HOLY", "HOME", "HONE", "HONK", "HOOD",
  "HOOK", "HOOP", "HOOT", "HOPE", "HOPS", "HORN", "HOSE", "HOST", "HOUR", "HOVE", "HOWL",
  "HUBS", "HUES", "HUFF", "HUGE", "HUGS", "HULA", "HULK", "HULL", "HUMS", "HUNG", "HUNT",
  "HURL", "HURT", "HUSH", "HUSK", "HUTS", "HYMN", "ICED", "ICES", "ICON", "IDEA", "IDLE",
  "IDLY", "IDOL", "INCH", "INFO", "INKS", "INKY", "INNS", "INTO", "IONS", "IOTA", "IRIS",
  "IRON", "ISLE", "ITCH", "ITEM", "JABS", "JACK", "JADE", "JAIL", "JAMS", "JARS", "JAWS",
  "JAZZ", "JEAN", "JEEP", "JEER", "JELL", "JERK", "JEST", "JETS", "JIBE", "JIGS", "JILT",
  "JINX", "JOBS", "JOCK", "JOGS", "JOIN", "JOKE", "JOLT", "JOSH", "JOTS", "JOWL", "JOYS",
  "JUDO", "JUGS", "JULY", "JUMP", "JUNE", "JUNK", "JURY", "JUST", "JUTE", "KEEL", "KEEN",
  "KEEP", "KEPT", "KEYS", "KICK", "KIDS", "KILL", "KILN", "KILO", "KILT", "KIND", "KING",
  "KISS", "KITE", "KITS", "KNEE", "KNEW", "KNIT", "KNOB", "KNOT", "KNOW", "LABS", "LACE",
  "LACK", "LACY", "LADS", "LADY", "LAID", "LAIR", "LAKE", "LAMB", "LAME", "LAMP", "LAND",
  "LANE", "LANK", "LAPS", "LARD", "LARK", "LASH", "LASS", "LAST", "LATE", "LAUD", "LAVA",
  "LAWN", "LAWS", "LAYS", "LAZE", "LAZY", "LEAD", "LEAF", "LEAK", "LEAN", "LEAP", "LEFT",
  "LEGS", "LEND", "LENS", "LENT", "LESS", "LEST", "LETS", "LEVY", "LEWD", "LIAR", "LICE",
  "LICK", "LIDS", "LIED", "LIEN", "LIES", "LIFE", "LIFT", "LIKE", "LILY", "LIMB", "LIME",
  "LIMP", "LINE", "LINK", "LINT", "LION", "LIPS", "LISP", "LIST", "LIVE", "LOAD", "LOAF",
  "LOAM", "LOAN", "LOBE", "LOCH", "LOCK", "LODE", "LOFT", "LOGS", "LOIN", "LONE", "LONG",
  "LOOK", "LOOM", "LOOP", "LORE", "LOSE", "LOSS", "LOST", "LOTS", "LOUD", "LOVE", "LOWS",
  "LUCK", "LUMP", "LUNG", "LURE", "LURK", "LUSH", "LUST", "LUTE", "LYRE", "MACE", "MADE",
  "MAID", "MAIL", "MAIN", "MAKE", "MALE", "MALT", "MANE", "MANY", "MAPS", "MARE", "MARK",
  "MARS", "MASH", "MASK", "MASS", "MAST", "MATE", "MATH", "MATS", "MAUL", "MAZE", "MEAD",
  "MEAL", "MEAN", "MEAT", "MEED", "MEEK", "MEET", "MELT", "MEND", "MENU", "MEOW", "MERE",
  "MESH", "MESS", "METE", "MICE", "MILD", "MILE", "MILK", "MILL", "MIME", "MIND", "MINE",
  "MINI", "MINT", "MINX", "MIRE", "MIST", "MITE", "MOAN", "MOAT", "MOCK", "MODE", "MOLD",
  "MOLE", "MOLT", "MONK", "MOOD", "MOON", "MOOR", "MOOT", "MOPE", "MORE", "MOSS", "MOST",
  "MOTE", "MOTH", "MOVE", "MOWN", "MUCH", "MUDD", "MUDS", "MUFF", "MUGS", "MULE", "MULL",
  "MUSE", "MUSH", "MUSK", "MUST", "MUTE", "MYTH", "NAIL", "NAME", "NAVY", "NEAR", "NEAT",
  "NECK", "NEED", "NEON", "NEST", "NETS", "NEWS", "NEWT", "NEXT", "NICE", "NICK", "NIGH",
  "NINE", "NODE", "NODS", "NOEL", "NONE", "NOOK", "NOON", "NOPE", "NORM", "NOSE", "NOTE",
  "NOUN", "NOVA", "NUDE", "NUMB", "NUNS", "NUTS", "OAKS", "OARS", "OATH", "OATS", "OBEY",
  "ODOR", "OGRE", "OILS", "OILY", "OINT", "OKAY", "OMEN", "OMIT", "ONCE", "ONES", "ONLY",
  "ONTO", "ONUS", "OOZE", "OPAL", "OPEN", "ORAL", "ORBS", "ORCA", "ORES", "OTTER", "OUCH",
  "OURS", "OUST", "OVAL", "OVEN", "OVER", "OWED", "OWES", "OWLS", "OWNS", "OXEN", "PACE",
  "PACK", "PACT", "PAGE", "PAID", "PAIL", "PAIN", "PAIR", "PALE", "PALM", "PANE", "PANG",
  "PANS", "PANT", "PAPA", "PARK", "PART", "PASS", "PAST", "PATH", "PATS", "PEAK", "PEAL",
  "PEAR", "PEAS", "PEAT", "PECK", "PEEK", "PEEL", "PEEP", "PEER", "PELT", "PEND", "PENS",
  "PERK", "PEST", "PETS", "PIED", "PIER", "PIES", "PIGS", "PIKE", "PILE", "PILL", "PINE",
  "PING", "PINK", "PINS", "PINT", "PIPE", "PITS", "PITY", "PLAN", "PLAY", "PLEA", "PLED",
  "PLOT", "PLOW", "PLUG", "PLUM", "PLUS", "POEM", "POET", "POKE", "POLE", "POLL", "POND",
  "PONY", "POOL", "POOR", "POPE", "POPS", "PORE", "PORK", "PORT", "POSE", "POST", "POTS",
  "POUR", "POUT", "PRAY", "PREY", "PRIG", "PRIM", "PROD", "PROP", "PROS", "PROW", "PUFF",
  "PULL", "PULP", "PUMP", "PUNS", "PUPIL", "PUPS", "PURE", "PURR", "PUSH", "PUTT", "PUTS",
  "QUAY", "QUIT", "QUIZ", "RACE", "RACK", "RAFT", "RAGE", "RAGS", "RAID", "RAIL", "RAIN",
  "RAKE", "RAMP", "RAMS", "RANG", "RANK", "RANT", "RARE", "RASH", "RATE", "RATS", "RAVE",
  "RAYS", "RAZE", "READ", "REAL", "REAP", "REAR", "REED", "REEF", "REEK", "REEL", "REIN",
  "RELY", "RENT", "REST", "RIBS", "RICE", "RICH", "RIDE", "RIFE", "RIFT", "RIMS", "RING",
  "RINK", "RIPE", "RIPS", "RISE", "RISK", "RITE", "ROAD", "ROAM", "ROAR", "ROBE", "ROBS",
  "ROCK", "RODE", "RODS", "ROIL", "ROLE", "ROLL", "ROOF", "ROOM", "ROOT", "ROPE", "ROSE",
  "ROSY", "ROTE", "ROTS", "ROUT", "ROVE", "ROWS", "RUBE", "RUBS", "RUBY", "RUDE", "RUFF",
  "RUGS", "RUIN", "RULE", "RUMP", "RUNS", "RUNT", "RUSE", "RUSH", "RUST", "RUTS", "SACK",
  "SAFE", "SAGA", "SAGE", "SAID", "SAIL", "SAKE", "SALE", "SALT", "SAME", "SAND", "SANE",
  "SANG", "SANK", "SANS", "SAPS", "SASH", "SAVE", "SAWS", "SAYS", "SCAB", "SCAM", "SCAN",
  "SCAR", "SEAL", "SEAM", "SEAR", "SEAS", "SEAT", "SEED", "SEEK", "SEEM", "SEEN", "SEEP",
  "SEER", "SEES", "SELF", "SELL", "SEND", "SENT", "SETS", "SEWN", "SEWS", "SHED", "SHIN",
  "SHIP", "SHOE", "SHOP", "SHOT", "SHOW", "SHUN", "SHUT", "SICK", "SIDE", "SIFT", "SIGH",
  "SIGN", "SILK", "SILL", "SILO", "SILT", "SINE", "SING", "SINK", "SINS", "SIRE", "SITE",
  "SITS", "SIZE", "SKEW", "SKID", "SKIM", "SKIN", "SKIP", "SKIT", "SLAB", "SLAM", "SLAP",
  "SLAT", "SLAW", "SLED", "SLEW", "SLID", "SLIM", "SLIP", "SLIT", "SLOG", "SLOP", "SLOT",
  "SLOW", "SLUG", "SLUM", "SLUR", "SMOG", "SNAP", "SNIP", "SNOW", "SNUB", "SNUG", "SOAK",
  "SOAP", "SOAR", "SOCK", "SODA", "SOFA", "SOFT", "SOIL", "SOLD", "SOLE", "SOLO", "SOME",
  "SONG", "SONS", "SOON", "SOOT", "SORE", "SORT", "SOUL", "SOUP", "SOUR", "SOWN", "SOWS",
  "SPAM", "SPAN", "SPAR", "SPAT", "SPEW", "SPIN", "SPIT", "SPOT", "SPRY", "SPUD", "SPUR",
  "STAG", "STAR", "STAY", "STEM", "STEP", "STEW", "STIR", "STOP", "STUB", "STUD", "SUCH",
  "SUCK", "SUIT", "SULK", "SUNG", "SUNK", "SURE", "SURF", "SWAN", "SWAP", "SWAT", "SWAY",
  "SWIM", "TACK", "TACT", "TAIL", "TAKE", "TALE", "TALK", "TALL", "TAME", "TANK", "TAPE",
  "TAPS", "TART", "TASK", "TEAL", "TEAM", "TEAR", "TEAS", "TEAT", "TEEM", "TEEN", "TELL",
  "TENT", "TERM", "TEST", "TEXT", "THAT", "THEM", "THEN", "THEY", "THIN", "THIS", "THOU",
  "THUD", "THUG", "TICK", "TIDE", "TIDY", "TIED", "TIER", "TIES", "TILE", "TILL", "TILT",
  "TIME", "TINS", "TINT", "TINY", "TIPS", "TIRE", "TOAD", "TOED", "TOES", "TOIL", "TOLD",
  "TOLL", "TOMB", "TOME", "TONE", "TONS", "TOOK", "TOOL", "TOOT", "TOPS", "TORE", "TORN",
  "TOSS", "TOUR", "TOWN", "TOYS", "TRAP", "TRAY", "TREE", "TREK", "TRIM", "TRIO", "TRIP",
  "TROD", "TROT", "TRUE", "TUBE", "TUBS", "TUCK", "TUFT", "TUNA", "TUNE", "TURF", "TURN",
  "TUSK", "TWIG", "TWIN", "TYPE", "TYPO", "UNIT", "UNTO", "UPON", "URGE", "USED", "USER",
  "USES", "VAIN", "VALE", "VAMP", "VANE", "VANS", "VARY", "VASE", "VAST", "VEAL", "VEIL",
  "VEIN", "VENT", "VERB", "VERY", "VEST", "VETO", "VIAL", "VICE", "VIEW", "VINE", "VISA",
  "VISE", "VOID", "VOLT", "VOTE", "VOWS", "WADE", "WAGE", "WAIL", "WAIT", "WAKE", "WALK",
  "WALL", "WAND", "WANT", "WARD", "WARM", "WARN", "WARS", "WART", "WASH", "WASP", "WAVE",
  "WAVY", "WAYS", "WEAK", "WEAN", "WEAR", "WEBS", "WEED", "WEEK", "WEEP", "WELD", "WELL",
  "WENT", "WEPT", "WERE", "WEST", "WETS", "WHAT", "WHEAT", "WHEW", "WHIM", "WHIP", "WHIZ",
  "WHOA", "WHOM", "WIDE", "WIFE", "WILD", "WILL", "WILT", "WIND", "WINE", "WING", "WINK",
  "WINS", "WIPE", "WIRE", "WIRY", "WISE", "WISH", "WISP", "WITH", "WOLF", "WOMB", "WONT",
  "WOOD", "WOOF", "WOOL", "WORD", "WORE", "WORK", "WORM", "WORN", "WRAP", "WREN", "YARD",
  "YARN", "YAWN", "YEAR", "YELL", "YOGA", "YOKE", "YOLK", "YOUR", "ZEAL", "ZERO", "ZINC", "ZONE",

  // 5-Letter Words (Classic & Comprehensive)
  "ABOUT", "ABOVE", "ABUSE", "ACTOR", "ACUTE", "ADAPT", "ADMIT", "ADOPT", "ADULT", "AFTER",
  "AGAIN", "AGENT", "AGREE", "AHEAD", "ALARM", "ALBUM", "ALERT", "ALIKE", "ALIVE", "ALLOW",
  "ALONE", "ALONG", "ALTER", "AMONG", "ANGER", "ANGLE", "ANGRY", "APART", "APPLE", "APPLY",
  "ARENA", "ARGUE", "ARISE", "ARMED", "ARMOR", "ARROW", "ASIDE", "ASSET", "AUDIO", "AUDIT",
  "AVOID", "AWAIT", "AWAKE", "AWARD", "AWARE", "BADLY", "BAKER", "BASES", "BASIC", "BASIS",
  "BEACH", "BEGAN", "BEGIN", "BEGUN", "BEING", "BELOW", "BENCH", "BILLY", "BIRTH", "BLACK",
  "BLAME", "BLIND", "BLOCK", "BLOOD", "BOARD", "BOAST", "BOOST", "BOOTH", "BOUND", "BRAIN",
  "BRAND", "BRASS", "BRAVE", "BREAD", "BREAK", "BREED", "BRIEF", "BRING", "BROAD", "BROKE",
  "BROWN", "BUILD", "BUILT", "BUYER", "CABLE", "CALIF", "CANDY", "CARRY", "CATCH", "CAUSE",
  "CHAIN", "CHAIR", "CHAMP", "CHART", "CHASE", "CHEAP", "CHECK", "CHEST", "CHIEF", "CHILD",
  "CHINA", "CHOSE", "CIVIL", "CLAIM", "CLASS", "CLEAN", "CLEAR", "CLICK", "CLOCK", "CLOSE",
  "COACH", "COAST", "COULD", "COUNT", "COURT", "COVER", "CRAFT", "CRASH", "CREAM", "CRIME",
  "CROSS", "CROWD", "CROWN", "CUBIC", "CYBER", "CYCLE", "DAILY", "DANCE", "DATED", "DEALT",
  "DEATH", "DEBUT", "DELAY", "DELTA", "DEPTH", "DOING", "DOUBT", "DOZEN", "DRAFT", "DRAMA",
  "DRAWN", "DREAM", "DRESS", "DRIFT", "DRINK", "DRIVE", "DROVE", "DYING", "EAGER", "EAGLE",
  "EARLY", "EARTH", "EIGHT", "ELITE", "EMPTY", "ENEMY", "ENJOY", "ENTER", "ENTRY", "EQUAL",
  "ERROR", "EVENT", "EVERY", "EXACT", "EXIST", "EXTRA", "FAITH", "FALSE", "FAULT", "FIBER",
  "FIELD", "FIFTH", "FIFTY", "FIGHT", "FINAL", "FIRST", "FIXED", "FLASH", "FLEET", "FLOOR",
  "FLUID", "FOCUS", "FORCE", "FORTH", "FORTY", "FORUM", "FOUND", "FRAME", "FRANK", "FRAUD",
  "FRESH", "FRONT", "FRUIT", "FULLY", "FUNNY", "GIANT", "GIVEN", "GLASS", "GLOBE", "GOING",
  "GRACE", "GRADE", "GRAND", "GRANT", "GRASS", "GREAT", "GREEN", "GROSS", "GROUP", "GROWN",
  "GUARD", "GUESS", "GUEST", "GUIDE", "HAPPY", "HARRY", "HASTE", "HEART", "HEAVY", "HENCE",
  "HENRY", "HORSE", "HOTEL", "HOUSE", "HUMAN", "IDEAL", "IMAGE", "INDEX", "INNER", "INPUT",
  "ISSUE", "JAPAN", "JIMMY", "JOINT", "JONES", "JUDGE", "KNOWN", "LABEL", "LARGE", "LASER",
  "LATER", "LAUGH", "LAYER", "LEARN", "LEASE", "LEAST", "LEAVE", "LEGAL", "LEVEL", "LEWIS",
  "LIGHT", "LIMIT", "LINKS", "LIVES", "LOCAL", "LOGIC", "LOOSE", "LOWER", "LUCKY", "LUNAR",
  "LUNCH", "MAGIC", "MAJOR", "MAKER", "MARCH", "MATCH", "MAYOR", "MEANT", "MEDIA", "METAL",
  "MIGHT", "MINOR", "MINUS", "MIXED", "MODEL", "MONEY", "MONTH", "MORAL", "MOTOR", "MOUNT",
  "MOUSE", "MOUTH", "MOVIE", "MUSIC", "NEEDS", "NEVER", "NEWLY", "NIGHT", "NINJA", "NOISE",
  "NORTH", "NOTED", "NOVEL", "NURSE", "OCCUR", "OCEAN", "OFFER", "OFTEN", "ORDER", "OTHER",
  "OUGHT", "PAINT", "PANEL", "PAPER", "PARTY", "PEACE", "PETER", "PHASE", "PHONE", "PHOTO",
  "PIECE", "PILOT", "PIXEL", "PITCH", "PLACE", "PLAIN", "PLANE", "PLANT", "PLATE", "POINT",
  "POUND", "POWER", "PRESS", "PRICE", "PRIDE", "PRIME", "PRINT", "PRISM", "PRIOR", "PRIZE",
  "PROOF", "PROUD", "PROVE", "PULSE", "QUEEN", "QUICK", "QUIET", "QUITE", "RADIO", "RAISE",
  "RANGE", "RAPID", "RATIO", "RAVEN", "REACH", "READY", "REFER", "RIGHT", "RIVAL", "RIVER",
  "ROBIN", "ROBOT", "ROUND", "ROUTE", "ROYAL", "RURAL", "SCALE", "SCENE", "SCOPE", "SCORE",
  "SENSE", "SERVE", "SETUP", "SEVEN", "SHALL", "SHAPE", "SHARE", "SHARP", "SHEET", "SHELF",
  "SHELL", "SHIFT", "SHINE", "SHIRT", "SHOCK", "SHOOT", "SHORT", "SHOWN", "SIGHT", "SINCE",
  "SIXTH", "SIXTY", "SIZED", "SKILL", "SLEEP", "SLIDE", "SMALL", "SMART", "SMILE", "SMOKE",
  "SOLID", "SOLVE", "SORRY", "SOUND", "SOUTH", "SPACE", "SPARK", "SPEAK", "SPEED", "SPEND",
  "SPENT", "SPLIT", "SPOKE", "SPORT", "STAFF", "STAGE", "STAKE", "STAND", "START", "STATE",
  "STEAM", "STEEL", "STICK", "STILL", "STOCK", "STONE", "STOOD", "STORM", "STORY", "STRIP",
  "STUCK", "STUDY", "STUFF", "STYLE", "SUGAR", "SUITE", "SUPER", "SWEET", "SWIFT", "SWORD",
  "TABLE", "TAKEN", "TASTE", "TAXES", "TEACH", "TEETH", "TERRY", "TEXAS", "THANK", "THEFT",
  "THEIR", "THEME", "THERE", "THESE", "THICK", "THING", "THINK", "THIRD", "THOSE", "THREE",
  "THREW", "THROW", "TIGER", "TIGHT", "TIMES", "TIRED", "TITLE", "TODAY", "TOPIC", "TOTAL",
  "TOUCH", "TOUGH", "TOWER", "TRACK", "TRADE", "TRAIN", "TREAT", "TREND", "TRIAL", "TRIED",
  "TRIES", "TRUCK", "TRULY", "TRUST", "TRUTH", "TWICE", "UNDER", "UNDUE", "UNION", "UNITY",
  "UNTIL", "UPPER", "UPSET", "URBAN", "USAGE", "USUAL", "VALID", "VALUE", "VIDEO", "VIPER",
  "VIRUS", "VISIT", "VITAL", "VOICE", "WASTE", "WATCH", "WATER", "WHEEL", "WHERE", "WHICH",
  "WHILE", "WHITE", "WHOLE", "WHOSE", "WOMAN", "WOMEN", "WORLD", "WORRY", "WORSE", "WORST",
  "WORTH", "WOULD", "WOUND", "WRITE", "WRONG", "WROTE", "YIELD", "YOUNG", "YOUTH",

  // 6-Letter Words
  "ACTION", "ACTIVE", "ACTUAL", "ADVICE", "AFFECT", "AFFORD", "AFRAID", "AGENCY", "AGENDA",
  "ALMOST", "ALWAYS", "AMOUNT", "ANIMAL", "ANNUAL", "ANSWER", "ANYONE", "ANYWAY", "APPEAL",
  "APPEAR", "AROUND", "ARRIVE", "ARTIST", "ASPECT", "ASSUME", "ATTACK", "ATTEND", "AUGUST",
  "AUTHOR", "AVENUE", "BARELY", "BATTLE", "BEAUTY", "BECOME", "BEFORE", "BEHIND", "BELIEF",
  "BELONG", "BESIDE", "BETTER", "BEYOND", "BORDER", "BORROW", "BOTHER", "BOTTLE", "BOTTOM",
  "BOUGHT", "BRANCH", "BREATH", "BRIDGE", "BRIGHT", "BROKEN", "BUDGET", "BURDEN", "BUREAU",
  "BUTTON", "CAMERA", "CANCER", "CANDLE", "CANNOT", "CARBON", "CAREER", "CASTLE", "CASUAL",
  "CAUGHT", "CENTER", "CHANCE", "CHANGE", "CHARGE", "CHOICE", "CHOOSE", "CHURCH", "CIRCLE",
  "CLIENT", "CLOSED", "CLOSER", "COFFEE", "COLUMN", "COMBAT", "COMING", "COMMON", "COMPLY",
  "COPPER", "CORNER", "COSTLY", "COUNTY", "COUPLE", "COURSE", "COUSIN", "CREDIT", "CRISIS",
  "CUSTOM", "DAMAGE", "DANGER", "DEALER", "DECADE", "DECIDE", "DEFEAT", "DEFEND", "DEFINE",
  "DEGREE", "DEPUTY", "DESERT", "DESIGN", "DESIRE", "DETAIL", "DETECT", "DEVICE", "DIFFER",
  "DINNER", "DIRECT", "DOCTOR", "DOLLAR", "DOMAIN", "DOUBLE", "DRIVEN", "DRIVER", "DURING",
  "EASILY", "EATING", "EDITOR", "EFFECT", "EFFORT", "EIGHTH", "EITHER", "ELEVEN", "EMERGE",
  "EMPIRE", "EMPLOY", "ENABLE", "ENDING", "ENERGY", "ENGINE", "ENOUGH", "ENSURE", "ENTIRE",
  "ENTITY", "EQUITY", "ESCAPE", "ESTATE", "ETHICS", "EXCEED", "EXCEPT", "EXCUSE", "EXPAND",
  "EXPECT", "EXPERT", "EXPORT", "EXTEND", "EXTENT", "FABRIC", "FACTOR", "FAILED", "FAIRLY",
  "FAMILY", "FAMOUS", "FATHER", "FELLOW", "FEMALE", "FIGURE", "FILING", "FINGER", "FINISH",
  "FISCAL", "FLIGHT", "FLOWER", "FLYING", "FOLLOW", "FORBID", "FORCED", "FOREST", "FORGET",
  "FORMAT", "FORMER", "FOSTER", "FOUGHT", "FOURTH", "FREEZE", "FRIEND", "FUTURE", "GALAXY",
  "GARDEN", "GATHER", "GENDER", "GENTLE", "GERMAN", "GLOBAL", "GOLDEN", "GROUND", "GROWTH",
  "GUILTY", "HANDED", "HANDLE", "HAPPEN", "HARBOR", "HARDLY", "HEADED", "HEALTH", "HEARING",
  "HEAVEN", "HEIGHT", "HELPED", "HERSELF", "HIDDEN", "HOLDER", "HONEST", "IMPACT", "IMPORT",
  "INCOME", "INDEED", "INJURY", "INSIDE", "INTEND", "INVEST", "ISLAND", "ITSELF", "JACKET",
  "JUNIOR", "KILLED", "KNIGHT", "LABOR", "LACKED", "LADDER", "LADIES", "LANCER", "LANDED",
  "LAPTOP", "LARGELY", "LATEST", "LATTER", "LAUGH", "LAUNCH", "LAWYER", "LEADER", "LEAGUE",
  "LEAVES", "LEGACY", "LEGEND", "LENDER", "LENGTH", "LESSON", "LETTER", "LIGHTS", "LIKELY",
  "LINKED", "LIQUID", "LISTEN", "LITTLE", "LIVING", "LOADED", "LOCATE", "LOCKED", "LONGER",
  "LOOKED", "LOSING", "LOVELY", "LOVING", "LUMBER", "LUXURY", "MAGNET", "MAINLY", "MAKING",
  "MANAGE", "MANNER", "MANUAL", "MARGIN", "MARINE", "MARKET", "MASTER", "MATTER", "MATURE",
  "MEDIUM", "MEMBER", "MEMORY", "MENTAL", "MERELY", "MERGER", "METHOD", "MIDDLE", "MILLER",
  "MINING", "MINUTE", "MIRROR", "MOBILE", "MODERN", "MODIFY", "MODULE", "MOMENT", "MORTAL",
  "MOSTLY", "MOTHER", "MOTION", "MOVING", "MURDER", "MUSEUM", "MUTUAL", "MYSELF", "NATION",
  "NATIVE", "NATURE", "NEARBY", "NEEDLE", "NEPHEW", "NERVOUS", "NEWEST", "NEWSPAPER", "NIGHTS",
  "NOBODY", "NORMAL", "NOTICE", "NOTION", "NUMBER", "OBJECT", "OBTAIN", "OFFICE", "OFFSET",
  "ONLINE", "OPENED", "OPTION", "ORANGE", "ORIGIN", "OUTPUT", "PACKED", "PALACE", "PARENT",
  "PARTLY", "PATENT", "PEOPLE", "PERIOD", "PERMIT", "PERSON", "PHRASE", "PICKED", "PICTURE",
  "PLANET", "PLAYER", "PLEASE", "PLENTY", "POCKET", "POETRY", "POLICE", "POLICY", "POORLY",
  "PRAYER", "PREFER", "PRETTY", "PRINCE", "PRISON", "PROFIT", "PROPER", "PROVE", "PUBLIC",
  "PURSUE", "PUZZLE", "RABBIT", "RADICAL", "RANDOM", "RARELY", "RATHER", "RATING", "READER",
  "REALLY", "REASON", "RECALL", "RECENT", "RECORD", "REDUCE", "REFORM", "REGARD", "REGIME",
  "REGION", "RELATE", "RELIEF", "REMAIN", "REMOTE", "REMOVE", "REPAIR", "REPEAT", "REPLACE",
  "REPORT", "RESCUE", "RESIGN", "RESIST", "RESORT", "RESULT", "RETAIL", "RETAIN", "RETURN",
  "REVEAL", "REVIEW", "REWARD", "RISING", "ROBUST", "ROCKET", "ROUTINE", "RUNNER", "SAFETY",
  "SALARY", "SAMPLE", "SAVING", "SCHEME", "SCHOOL", "SCREEN", "SCRIPT", "SEARCH", "SEASON",
  "SECOND", "SECRET", "SECTOR", "SECURE", "SEEING", "SELECT", "SELLER", "SENIOR", "SERIES",
  "SERIOUS", "SERVER", "SETTLE", "SEVERE", "SHADOW", "SHARED", "SHIELD", "SHOULD", "SILENT",
  "SILVER", "SIMPLE", "SIMPLY", "SINGLE", "SISTER", "SLIGHT", "SMOOTH", "SOCIAL", "SOLELY",
  "SOUGHT", "SOURCE", "SOVIET", "SPEECH", "SPIRIT", "SPREAD", "SPRING", "SQUARE", "STABLE",
  "STATUS", "STEADY", "STOLEN", "STRAIN", "STREAM", "STREET", "STRESS", "STRICT", "STRIKE",
  "STRING", "STRONG", "STRUCK", "STUDIO", "SUBMIT", "SUDDEN", "SUFFER", "SUMMER", "SUMMIT",
  "SUPPLY", "SURELY", "SURVEY", "SWITCH", "SYMBOL", "SYSTEM", "TAKING", "TALENT", "TARGET",
  "TAUGHT", "TENANT", "TENDER", "TENNIS", "TERMS", "TERROR", "THANKS", "THEORY", "THIRTY",
  "THREAT", "TIMING", "TISSUE", "TITLE", "TODAY", "TONIGHT", "TOPIC", "TOWARD", "TRAGIC",
  "TRAVEL", "TREATY", "TRENDY", "TRIAL", "TRIPLE", "TROPHY", "TRUCKS", "TRYING", "TUNNEL",
  "TURNING", "TWELVE", "TWENTY", "UNABLE", "UNIQUE", "UNITED", "UNLESS", "UNLIKE", "UPDATE",
  "USEFUL", "VALLEY", "VALUED", "VARIED", "VICTIM", "VICTOR", "VIEWER", "VIOLET", "VIRTUE",
  "VISION", "VISUAL", "VOLUME", "WALKER", "WALLET", "WANTED", "WARMTH", "WEAKEN", "WEALTH",
  "WEAPON", "WEEKLY", "WEIGHT", "WINDOW", "WINNER", "WINTER", "WISDOM", "WONDER", "WOODEN",
  "WORKER", "WRITER", "YELLOW", "ZEALOT"
];

// Quick index set for instant O(1) membership check
export const VOCABULARY_SET = new Set(COMMON_VOCABULARY.map((w) => w.toUpperCase()));

/**
 * Check if candidate word can be formed from available letter bag
 */
export function canFormFromLetters(candidate, availableLetters) {
  if (!candidate || !availableLetters) return false;
  const cand = candidate.trim().toUpperCase();
  const avail = availableLetters.trim().toUpperCase();
  if (cand.length < 3 || cand.length > avail.length) return false;

  const freq = {};
  for (const c of avail) freq[c] = (freq[c] || 0) + 1;
  for (const c of cand) {
    if (!freq[c] || freq[c] <= 0) return false;
    freq[c]--;
  }
  return true;
}

